### PR TITLE
Add Russian and Ukrainian locale

### PR DESCRIPTION
**Pull request by koresar**
As promised (2 years ago) I made the Ukrainian and Russian locales.

### CODE REVIEW

**Comment by mixmix** [comment]
this looks great!
So you know, @mmckegg has been traveling so will get to this when he's more stable.

**Comment by mmckegg** [comment]
Thanks @koresar, will be included in the next release!

**Comment by guland2000** [comment]
Already 2019... So, where is Russian language inside of app?

**Comment by christianbundy** [comment]
@guland2000 

When you open Patchwork you'll select *More*, then *Settings*, then you should be able to select the language you'd like to use.

**Pull request merged**
