### PR TITLE
fix locale fr.json

### PR DESCRIPTION
**Pull request by vtexier**
* Translate Liked correctly (Capitalized)
* Add "new" translation

### CODE REVIEW

**Comment by black-puppydog** [comment]
hey @vtexier apparently we managed to fix travis. can you rebase this?
by the way, this PR conflicts with #1273. I trust your language skills more than mine, but if you look at that PR, it also includes further strings missing from the French translation. In case you get bored at home. :laughing:

**Comment by vtexier** [comment]
Ok, I have removed the "Liked" (Capitalized) causing conflict, and removed the non used "liked" key.

I have left the missing "new" key, as if conflict it is simple to merge both.

**Comment by black-puppydog** [comment]
ah, that was not what I meant. I was happy to expire my PR and just let you do your French. you're better at it than I am :D

**Comment by black-puppydog** [comment]
one more question though: how did you determin that `"liked"` was unused? 
I find one usage of it in `lib/depject/message/html/render/vote.js`:

https://github.com/ssbc/patchwork/blob/d33ad4736567a2417f9494160d50f1e900caecd2/lib/depject/message/html/render/vote.js#L42

but I find it *super* hard to trace the call paths in the code base. 

I don't know what I'm doing meme

**Comment by vtexier** [comment]
Ooops, I had no idea "liked" was used elsewhere. But in Patchwork, I got a Capitalized "Liked" not translated in french, and I see a "liked" not Capitalized in the json file so I thought, hey that the "L" that is a typo and the translator do not find the key.

But your finding prove me wrong... So let me know if you prefer i do all the french PR be myself.
I will cherry pick the other french PR and fix all I know...

**Comment by black-puppydog** [comment]
Sure, go ahead, that way at least it will be true French. :)
Let me know if you're unclear about where & in which context the messages appear. Like I said, it's not always clear.

**Pull request merged**
