### PR TITLE
Fix errors in Esperanto language translation

### PR DESCRIPTION
**Pull request by qubist**

### CODE REVIEW

**Comment by christianbundy** [comment]
@qubist Is this something you'd like review on? I didn't open it because it's listed as a draft.

**Comment by qubist** [comment]
@christianbundy This is ready to be merged, I just figured I'd collect up a bunch of fixes in a draft pr, then merge them at once. That said, I haven't found errors since having that idea so maybe it's time to merge this, and I'll make a new pull request if I find errors in the future.

**Comment by christianbundy** [comment]
Totally up to you, I just wanted to make sure you weren't waiting on me for anything. Feel free to mark it *ready for review* whenever you'd like a review and we'll merge it in. :heart:

**Comment by christianbundy** [comment]
I'm going to merge this real quick so it isn't open -- hope you don't mind!

**Pull request merged**
