### PR TITLE
Update package.json - fixed a dependency issue

### PR DESCRIPTION
**Pull request by elanperach**
fixed this issue - https://github.com/dominictarr/stream-to-pull-stream/issues/8

### CODE REVIEW

**Comment by pfraze** [comment]
`^1.6.1` will install `1.6.6`, why the change?

**Comment by elanperach** [comment]
Because it installed 1.7.1 - which didn't work.

**Comment by elanperach** [comment]
I meant 1.6.7

**Comment by pfraze** [comment]
Ah, hm, sorry about that. Yeah, 1.6.7 is broken -- I'll try to get dominic to fix that soon

**Comment by elanperach** [comment]
No worries, was able to get it up and running :)

**Comment by dominictarr** [comment]
this should be fixed now, can you confirm @elanperach ?

**Comment by elanperach** [comment]
@dominictarr - working fine now. Thanks!

**Pull request closed without merging**
