### PR TITLE
update sbot 11.3.0 + new plugins

### PR DESCRIPTION
**Pull request by mixmix**
These are all now in master in Patchbay + Ticktack.
The problem is that when I open Patchwork now, it re-indexes all these plugins because of the different versions we're running. It makes switching btwn Patchwork and these other apps pretty much intolerable.

I think this is a broader conversation that we might need to have - as in what's our strategy here in the short and long term

:heart: :cactus:

### CODE REVIEW

**Comment by cryptix** [comment]
Ran this through the whole day and worked fine afaict.

**Comment by mixmix** [comment]
I think there are now newer sbot versions out.

**Comment by mmckegg** [comment]
@mixmix I think that the recently merged #789 has updated these. Closing!

**Comment by mixmix** [comment]
Cool!

**Pull request closed without merging**
