### PR TITLE
Migrate from Gossip to CONN

### PR DESCRIPTION
**Pull request by staltz**
This PR drops `ssb-legacy-conn` and `ssb-gossip` in favor of the newer `ssb-conn`. The APIs in Patchwork have been adapted to support ssb-conn, and it was rather straightforward. In some cases there some code was deleted, because equivalent functionality exists already in ssb-conn.

Things that are noticeably different to the users:

- **A "Suggested peers" section appears when there are staged peers**
- **LAN strangers are staged**
  - Strangers in the same LAN are not automatically connected to anymore, instead they appear as "Suggested peers" and the user must explicitly follow (while LAN friends are automatically connected to, like before)
- ~~**New pubs in the database are staged**~~
  - ~~New pubs discovered from the local database are not automatically connected to anymore, instead they appear as "Suggested peers" and the user must explicitly follow (but old pubs are connected to automatically, like before)~~
  - Actually, this was kept as before, because doing this change would require more UX work in Patchwork
- **Scheduling details**
  - The order and frequency which connections are scheduled may be slightly different, most users won't perceive it, but perhaps others will

### Recommended order of reviewing this PR

1. [package.json](https://github.com/ssbc/patchwork/pull/1178/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)
1. [lib/server-process.js](https://github.com/ssbc/patchwork/pull/1178/files#diff-daa8a4c465d62068e3c13b1bbfec2abe)
1. [lib/depject/sbot.js](https://github.com/ssbc/patchwork/pull/1178/files#diff-e477a745237d84f07e034a47f297cff6)
1. [lib/depject/invite/invite.js](https://github.com/ssbc/patchwork/pull/1178/files#diff-b08f0a1153ef8158dddef7998aa3d8f8)
1. [lib/plugins/index.js](https://github.com/ssbc/patchwork/pull/1178/files#diff-3ac0abd367a742dd9211f7d1fde579cf)
1. [index.js](https://github.com/ssbc/patchwork/pull/1178/files#diff-168726dbe96b3ce427e7fedce31bb0bc)
1. [lib/depject/page/html/render/public.js](https://github.com/ssbc/patchwork/pull/1178/files#diff-b77bd78272ed63762c5de8e553b2a4ab)
1. [styles/base/profile-list.mcss](https://github.com/ssbc/patchwork/pull/1178/files#diff-7e56987200a620276ef020c0ec5e3930)
1. [locales/en.json](https://github.com/ssbc/patchwork/pull/1178/files#diff-772a593ff61f0e484d43cc349a5ab31c)
1. [package-lock.json](https://github.com/ssbc/patchwork/pull/1178/files#diff-32607347f8126e6534ebc7ebaec4853d)

As soon as this PR is merged, I'll make a PR for adding support for rooms. [The code is ready here](https://github.com/ssbc/patchwork/commit/a5eb3d7ed1e7fc94bccdfb64388d144fd7376909), I just didn't want to blend it into this PR.

### CODE REVIEW

**Comment by christianbundy** [comment]
This looks great! I know @cinnamon-bun was having problems with ssb-legay-conn after 1.0.12 (including 2.x.x), I'd love their review before merging. :+1:

**Comment by staltz** [comment]
That's quite an old version, and ssb-conn is way ahead than ssb-legacy-conn, so yeah, just open up this branch and then `npm i && npm start` to test. I'm using it here locally and seems solid.

**Comment by cinnamon-bun** [comment]
Thanks for the hard work on this!  I have some high level questions.  I tried this out using a fresh user profile.

* The sidebar section is called "Suggested". It's pretty unclear this means "Peers and pubs you might want to make network connections to", and how it's different than the "Who to follow" section.  Could it be called... "Pubs to sync with"?
* Is there a way to connect to a pub for syncing without following it?  I like to unfollow all the pubs to avoid getting all their members in my friends-of-friends, but that means now I won't sync with anyone.  In general I do want to connect to most pubs and I don't want to follow them.
* Manyverse saw my laptop and put it in staging.  I chose Connect from Manyverse and my laptop account turned white with an orange dot.  On the laptop, I never saw my phone show up.  (I've also been having this problem with Patchwork 3.16.2, though it did once work on my network.  Not sure what's going on here.)
* Is the Suggested section limited to 4 items?  Maybe my phone is showing up but it would have been item number 5?

I wonder what a good default stance would be for connecting to pubs.  Maybe "auto-connect to pubs my friends are using; ask about the rest"?

And then we'd want to remember the pubs you've chosen to connect to...

Someday I think we'll want a pub management screen in the settings, listing all the pubs you know about and your stance on each one (following, followed by, connect to?)

MacOS 10.11.6

**Comment by staltz** [comment]
Thanks for the review @cinnamon-bun 

> The sidebar section is called "Suggested". It's pretty unclear this means "Peers and pubs you might want to make network connections to", and how it's different than the "Who to follow" section. Could it be called... "Pubs to sync with"?

Good point, I think in hindsight "Suggested" is quite a bad name. Spelling it out verbosely, it's (as you suggested) "Peers and pubs you might want to make network connections to", and it includes: pubs, peers in rooms, LAN peers, (in the future:) Bluetooth peers. So it can't be "Pubs to sync with" because that would be too narrow. Maybe "Staged peers"? Or "Suggested connections"?

> Is there a way to connect to a pub for syncing without following it? I like to unfollow all the pubs to avoid getting all their members in my friends-of-friends, but that means now I won't sync with anyone. In general I do want to connect to most pubs and I don't want to follow them.

Zooming out a bit from this question, I think Patchwork overall needs some product design rework or careful consideration. There are a lot of assumptions around pubs and accounts. For instance, in many other screens there are descriptions that recommend you to "connect to pubs", which is quite limiting once we want to expand from pubs to rooms and Bluetooth and DHT invites, etc. On the other hand, Patchwork also assumes that anything that has an SSB id is a "person". E.g. if you hover over a connected pub, it might say "you are not friends with this **person**", even though it's not actually a person. And then, with the addition of rooms, these are not SSB accounts in any shape or form (they have no feed), so they should never be followed, and should not open as a profile account. They merely have an SSB id just to allow secret-stack (and secret-handshake) to establish onion-encrypted channels between room clients. Also the side bar needs a redesign. Between the "Join Pub" button and the List of Connected Pubs, there is the List of Channels. Why in between? They should probably be grouped together. The "Join Pub" button would also need to be redesigned to perhaps "Paste Invite" or "Claim Invite Code" so that it's more generic. And Patchwork has always needed multiple actions per connected pub. Currently it only supports "disconnect", but it should also have "forget" (a.k.a. old: `gossip.remove`, new `conn.forget`).

Rant aside, I think your suggestion is sensible, the hover button should be "Connect" not "Follow", because if you want to follow, you just press the peer to open their profile, and then press "follow" on their profile.

> Manyverse saw my laptop and put it in staging. I chose Connect from Manyverse and my laptop account turned white with an orange dot. On the laptop, I never saw my phone show up. (I've also been having this problem with Patchwork 3.16.2, though it did once work on my network. Not sure what's going on here.)

Super curious about this one. It should be working all fine, because both Manyverse and Patchwork (in this PR) are using latest ssb-lan. Try to open up Wireshark and let me know the UDP packets being transmitted on port 8008 if you can.

> Is the Suggested section limited to 4 items? Maybe my phone is showing up but it would have been item number 5?

I don't recall putting a total hard limit, but the suggested pubs are at most 3. I don't want to list thousands of suggested pubs at once. Instead, when the user dismisses some of them, new ones come in.

> Someday I think we'll want a pub management screen in the settings, listing all the pubs you know about and your stance on each one (following, followed by, connect to?)

Yes! That's been on my mind to do in Manyverse. We really need something like this, to have better control where your data is going.

**Comment by staltz** [comment]
Updated the PR to use the subtitle "Possible connections" for staged peers, and the button is now "Connect", not follow.

**Comment by cinnamon-bun** [comment]
@staltz I tried it out again.

Nice, "Connect" buttons make more sense to me.  Could the button expand to fill the right side of the div, to avoid misclicks in the margin around it?

It's rapidly connecting and dropping connections to pubs but it eventually settles on some.  Maybe it's not compatible with all the pubs, or it's revisiting everything in gossip.json?

I like "Possible connections" as a title.  Hmm, 💻⚡️💻 and 😃❤️😃 could be one way to communicate the connect vs follow distinction?

Agree about improving the sidebar organization.  All the pub and connection stuff belongs together, and Active Channels and Who To Follow belong together.  That doesn't have to be part of this PR.

In the Suggested section I think local peers and pubs mixed together?  I'm worried about pubs drowning out local peers?  Agree that eventually we need to redesign to show other connection types like Bluetooth too.  I like Manyverse's connection screen with different icons for connection types.

Using my main account I don't see any Possible Connections, is that because I've already connected to all the pubs from that account so they're pre-approved?

Using a fresh account I see lots of Possible Connections.  I can connect to some of them.  It forgets which ones I've connected to when I restart.

I had the MacOS firewall on yesterday, explaining my connection problems.  Fixed that; today my other laptop shows up but rapidly connects and disconnects no matter what version of Patchwork I run here.  The other laptop is running Patchwork 3.14.1.

(I wish things in the sidebar lingered for a while after disconnecting -- everything is jumping around and it's hard to click on anything!)

**Comment by staltz** [comment]
> Nice, "Connect" buttons make more sense to me. Could the button expand to fill the right side of the div, to avoid misclicks in the margin around it?

I'll do that!

> It's rapidly connecting and dropping connections to pubs but it eventually settles on some. Maybe it's not compatible with all the pubs, or it's revisiting everything in gossip.json?

It's revisiting every `"type": "pub"` message in your SSB log. This was already something the gossip plugin did, and Patchwork did too (see some deleted code in this PR), but now it's doing that for staging.

> Hmm, :computer: :zap: :computer:  and :smiley: :heart: :smiley: could be one way to communicate the connect vs follow distinction?

I like that!

> In the Suggested section I think local peers and pubs mixed together? I'm worried about pubs drowning out local peers? Agree that eventually we need to redesign to show other connection types like Bluetooth too.

Yeah, I'm kind of scratching my head with what to do in this PR. On one hand, this PR would make Patchwork less UX consistent than it currently is. On the other hand, to keep Patchwork's UX consistency we would need to change a great amount of stuff. E.g. you could be connected to Alice as a Room peer, and that would show up in the section "Connected to", but if you were connected to Alice as a LAN peer, she would show up in the "Local" section. Basically, "Connected to" should cover all the types of connections, given the title "*Connected to*", unless we opt for "Internet connections" instead.

> Using my main account I don't see any Possible Connections, is that because I've already connected to all the pubs from that account so they're pre-approved?

Yes

> Using a fresh account I see lots of Possible Connections. I can connect to some of them. It forgets which ones I've connected to when I restart.

I think this is a bug in ssb-conn, or around that. I should fix it soon.

> (I wish things in the sidebar lingered for a while after disconnecting -- everything is jumping around and it's hard to click on anything!)

Yep, this is precisely why I insisted with myself that I had to build smooth enter-or-exit animations in Manyverse.

**Comment by staltz** [comment]
PR updated:

One of the main things I updated was that I reverted the decision to stage the pubs, bringing back Patchwork's own scanning of the log for `type="pub"` messages. I figured that Patchwork was already bypassing the Gossip's plugin scan of the log, setting `ssbConfig.gossip.autoPopulate = false`, so I kept that behavior. In order to stage pubs, Patchwork would need more careful UX design. This should make it easier to merge this PR, since now usage of ssb-conn will only be noticed by users for: LAN peers, Room peers.

> Could the button expand to fill the right side of the div, to avoid misclicks in the margin around it?

Done

**Comment by black-puppydog** [comment]
This (and the rooms PR) works nicely for me. Been running it for like half an hour so far, no problems noticed. But also no code read by me, so there's that. :P
My phone and desktop cannot see each other on the LAN, so this went through the hermies room. But I've also been getting other updates, so connecting to pubs seems to work too.

**Comment by black-puppydog** [comment]
Uh-oh... I'm getting 

```Error {}
Error {}
Error {}
Error {}
Error {}
Error {}
Error {}
Error {}
Error {}
Error {}
Error {}
Error {}
Error {}
Error {}
```

by the thousands. This happened over night, without interaction from my side.
Before that it worked nicely...
I guess I'll revert to the `conn` branch (currently on `rooms`) to see if it happens again.

**Comment by staltz** [comment]
I'm not getting exactly that output, but something similar, and not by the thousands, and it doesn't crash Patchwork:

```
Exception thrown by PacketStream substream end handler Error {}
Error: unexpected end of parent stream
    at PacketStream.destroy (/home/staltz/oss/patchwork/node_modules/packet-stream/index.js:71:7)
    at PacketStream.write (/home/staltz/oss/patchwork/node_modules/packet-stream/index.js:133:41)
    at /home/staltz/oss/patchwork/node_modules/muxrpc/pull-weird.js:58:44
    at /home/staltz/oss/patchwork/node_modules/pull-stream/sinks/drain.js:20:24
    at /home/staltz/oss/patchwork/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/staltz/oss/patchwork/node_modules/packet-stream-codec/index.js:95:24
    at next (/home/staltz/oss/patchwork/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:14:9)
    at /home/staltz/oss/patchwork/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:16:41
    at Object.cb (/home/staltz/oss/patchwork/node_modules/packet-stream-codec/index.js:102:18)
    at drain (/home/staltz/oss/patchwork/node_modules/pull-reader/index.js:39:14)
```

**Comment by black-puppydog** [comment]
A different machine I had running over night (rooms branch, rebased on master) produced this:

```
Error replicating with @G20wv2IZkB7BA/LKe7WMuByop3++J0u9+Y32OoEVOj8=.ed25519:
   Error: stream ended with:0 but wanted:9
    at drain (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/pull-reader/index.js:43:26)
    at /scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/pull-reader/index.js:63:18
    at /scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/pull-inactivity/node_modules/pull-abortable
/index.js:35:11
    at /scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/pull-stream/throughs/through.js:19:9
    at Object.cb (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/pull-box-stream/index.js:127:18)
    at drain (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/pull-reader/index.js:39:14)
    at more (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/pull-reader/index.js:55:13)
    at /scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/pull-reader/index.js:66:9
    at /scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/pull-reader/index.js:114:13
    at drain (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/stream-to-pull-stream/index.js:126:1
8)
server error, from net:::ffff:127.0.0.1:39974~shs:
Error: shs.server: client hello invalid (phase 3). they dailed a wrong number - they didn't have our public key
    at abort (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/secret-handshake/protocol.js:82:45)
    at Object.cb (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/secret-handshake/protocol.js:95:
20)
    at drain (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/pull-reader/index.js:39:14)
    at more (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/pull-reader/index.js:55:13)
    at /scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/pull-reader/index.js:66:9
    at /scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/pull-reader/index.js:20:7
    at drain (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/stream-to-pull-stream/index.js:126:1
8)
    at Socket.<anonymous> (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/stream-to-pull-stream/i
ndex.js:135:5)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
Error replicating with @xxZeuBUKIXYZZ7y+CIHUuy0NOFXz2MhUBkHemr86S3M=.ed25519:
   Error: parent stream is closing
    at PacketStream.stream (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/packet-stream/index.js
:46:28)
    at Object.ws.remoteCall (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/muxrpc/stream.js:116:
17)
    at /scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/muxrpc/index.js:46:15
    at remoteCall (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/muxrpc/api.js:40:19)
    at EventEmitter.obj.(anonymous function) [as createHistoryStream] (/scratch/taurus/dwynen/applications/ssb_stuff/pa
tchwork/node_modules/muxrpc/api.js:25:18)
    at replicate (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/ssb-replicate/legacy.js:291:13)
    at EventEmitter.fallback (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/ssb-replicate/legacy
.js:351:7)
    at Object.onceWrapper (events.js:273:13)
    at EventEmitter.emit (events.js:182:13)
    at /scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/ssb-ebt/index.js:129:15
Error replicating with @xxZeuBUKIXYZZ7y+CIHUuy0NOFXz2MhUBkHemr86S3M=.ed25519:
   Error: parent stream is closing
    at PacketStream.stream (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/packet-stream/index.js
:46:28)
    at Object.ws.remoteCall (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/muxrpc/stream.js:116:
17)
    at /scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/muxrpc/index.js:46:15
    at remoteCall (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/muxrpc/api.js:40:19)
    at EventEmitter.obj.(anonymous function) [as createHistoryStream] (/scratch/taurus/dwynen/applications/ssb_stuff/pa
tchwork/node_modules/muxrpc/api.js:25:18)
    at replicate (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/ssb-replicate/legacy.js:291:13)
    at EventEmitter.fallback (/scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/ssb-replicate/legacy
.js:351:7)
    at Object.onceWrapper (events.js:273:13)
    at EventEmitter.emit (events.js:182:13)
    at /scratch/taurus/dwynen/applications/ssb_stuff/patchwork/node_modules/ssb-ebt/index.js:129:15
Error {}
```

This is the *entire* log after the usual startup output.
Just a single, lonely `Error {}` at the end there.

Side note: having (human readable) timestamps on log output would really be nice still... *goes to find old gh issue*

**Comment by staltz** [comment]
Updated this PR:

- updated ssb-conn to 0.10.2
- pressing the "Connect" button on a suggested peer will call just `sbot.conn.connect`, not `sbot.conn.remember`+`sbot.conn.connect`
  - remember+connect would cause the peer to be stored in the database, and we don't want to do that with LAN peers (LAN IPs are not supposed to be assumed fixed) or room peers

**Comment by trosel** [comment]
Regarding 

>Zooming out a bit from this question, I think Patchwork overall needs some product design rework or careful consideration. There are a lot of assumptions around pubs and accounts. For instance, in many other screens there are descriptions that recommend you to "connect to pubs", which is quite limiting once we want to expand from pubs to rooms and Bluetooth and DHT invites, etc. On the other hand, Patchwork also assumes that anything that has an SSB id is a "person". 

And 

>Hmm, 💻 ⚡️ 💻 and 😃 ❤️ 😃 could be one way to communicate the connect vs follow distinction?

It may be a good idea to develop universal icons / logos / diagrams for describing these different types of terms. 

Have a logo for

* pub
* direct friend connection
* room

that each illustrate what each one does in terms of storing data on your machine and what data you share to it.

**Comment by trosel** [comment]
Maybe emojis are good for this for now...

Room = 😃👋🏠👋😃 
Pub = 😃🤝🏠🤝😃
Direct Friend Connection = 😃🤝😃

(waving implies just saying "hi" / lighter connection that doesn't require you to commit as much?)
(handshake implies a strong and heavier connection?)

**Comment by christianbundy** [comment]
@black-puppydog Is this the branch giving you a hard time? If so, info on the bug would be super helpful here. I'd love to get this merged but I'm unsure about the status of it.

**Comment by christianbundy** [comment]
Anyone have objections to merging this PR? We're currently blocked from updating ssb-legacy-conn because of [a bug in newer versions](https://github.com/ssbc/patchwork/issues/1170#issuecomment-523283152) and I'm uncomfortable feeling marooned on an outdated package.

**Comment by staltz** [comment]
I've been using for more than a month Patchwork `rooms` branch which includes this branch, and don't see any problems when it comes to connections.

**Comment by Happy0** [comment]
Sounds like we're probably fine to merge this PR and probably the rooms branch too?

**Comment by black-puppydog** [comment]
Sorry all, I missed the last three posts/weeks on this one. Yes @christianbundy,  that's the branch that was giving me trouble. Still not sure what was happening there; somehow patchwork wasn't scuttling with pubs or another local patchwork instance (running the same feed ID...) until I also launched the manyverse app on the same network. Then it suddenly got all kinds of updates.

**Comment by black-puppydog** [comment]
The thread I wrote on this: `%xUzy2iYQBO/CN157+olmI9GmGQVPHkj5dwTZwFiqBWk=.sha256`
Cross-posting for convenience:

> I’m having two machines at home running the same identity in #patchwork (the #ssb-rooms branch) and both of them seem to have trouble scuttling. I could accept that they have trouble connecting to each other since they’re running the same feed ID, and that might break some assumptions in shs or somewhere else.
But they both seem to be missing out on gossip overall, not just with each other. For example, they are both connected to my personal pub, and even over that edge they don’t communicate. One of them is currently four posts behind the other. And for both of them, restarting patchwork habitually pulls in hours-old posts that should have been there before.
> 
> @andrestaltz any chance there’s something preventing ssb-conn from scuttling regularly after a while?

> I’m running the rooms branch (git tells me it’s cf0850315191485e8a8748a0413de1d84901db65) but rebased on an (outdated… 7df64e8e90ce9271367da60b42e38eb617645962) master.
I guess first I’ll update to the latest master. It’s time anyhow. :P

> Okay I rebased the rooms branch on the upgrade-deps branch. There was one conflict that I had to hand-resolve, about ssb-friends. Not sure why that had to be merged in manually, the diff for package.json and package.lock.json looks pretty trivial.
So we’ll see how it goes.

> There really seems to be something off with #patchwork after all. Maybe it’s the conn/rooms branch, or maybe it’s something else, but there’s something wrong.
I just woke up my laptop and let it idle for a while. No syncing, no new messages. It’s rare that nothing happens on the verse for nine hours straight. So I restart patchwork, wait a few minutes. *crickets*
> 
> Then I launch #manyverse on the same wifi, and suddenly there’s a flurry of messages streaming in. How do I debug? The terminal shows a bunch of replication errors. I don’t know though if these were from before or after I started manyverse…

And an attached log file: 
[log.txt](https://github.com/ssbc/patchwork/files/3804902/log.txt)

**Comment by staltz** [comment]
@black-puppydog Perhaps test with just one Patchwork? I think two sbots communicating with each other with the *same ID* is probably unsupported by the SSB stack overall (just not explicitly unsupported, but there's an assumption everywhere that the remote ID is different than yours).

**Comment by christianbundy** [comment]
I'd like to let this bake in master for a bit before a release, but I'm happy to finally merge this. Thanks everyone for all your time and energy on this PR!

**Pull request merged**
