### PR TITLE
Add Polish localisation

### PR DESCRIPTION
**Pull request by nabijaczleweli**
I've just one question WRT the translation: how is the `"on "` (L194) used? I only got to `plugs/message/html/layout/*.js` and failed to understand the code so I'ven't been able to test it accurately os I'ven't translated it.

BTW, you've marked Slovenian as `si` but it should be `sl` according to ISO-639-1.

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
Any updates on this? Is this repo maintained at all anymore (should I've added the translations elsewhere)?

**Comment by mmckegg** [comment]
Hey @nabijaczleweli!

Sorry, totally missed this when you posted it last month.

> how is the "on " (L194) used?

The only place this is used is for issues created on git repos hosted on ssb. Example:

screen shot 2018-05-18 at 11 44 04 am

SSB message ref: `%FRFevxVYAoKsIBWaFd/erYUijxY4xeugTcoEr0kOnuY=.sha256`

These are pretty rare, so not super important to localise. 

> BTW, you've marked Slovenian as si but it should be sl according to ISO-639-1.

Whoops! Would you be able to create an issue (or PR) to fix that?

---

Anyway, I'm happy to merge this now, or wait if you want to try translating that "on" with the additional context.

**Comment by nabijaczleweli** [comment]
I'd leave "on" in but it actually has a meaning ("he") in Polish so…
Anyway, this is good to go, will fix Slovenian in a separate PR.

**Comment by mmckegg** [comment]
Great, thanks @nabijaczleweli! Merging, will be in the next release! 🎉

**Pull request merged**
