### PR TITLE
Add attending gatherings view

### PR DESCRIPTION
**Pull request by mmckegg**
This PR adds a new gatherings view that only shows gatherings that you have selected "attending".

Screen Shot 2019-08-28 at 3 16 48 PM

You access it via More > Gatherings > Attending:

Screen Shot 2019-08-28 at 3 16 32 PM

Currently this view shows posts in the order the events were created. A future improvement could show the events in order of the gathering date, or ordered by when you clicked attending.

### CODE REVIEW

**Comment by Powersource** [comment]
Awesome!

But broke for me when I went back and forth a bit between All and Attending. Infinite scuttling, plus I got

```
Exception thrown by PacketStream substream end handler Error: unexpected end of parent stream
    at PacketStream.destroy (/home/me/prj/ssb/patchwork/node_modules/packet-stream/index.js:71)
    at PacketStream.write (/home/me/prj/ssb/patchwork/node_modules/packet-stream/index.js:133)
    at /home/me/prj/ssb/patchwork/node_modules/muxrpc/pull-weird.js:58
    at /home/me/prj/ssb/patchwork/node_modules/pull-stream/sinks/drain.js:20
    at /home/me/prj/ssb/patchwork/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17
    at Object.cb (/home/me/prj/ssb/patchwork/node_modules/packet-stream-codec/index.js:98)
    at drain (/home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:46)
    at /home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:63
    at drain (/home/me/prj/ssb/patchwork/node_modules/stream-to-pull-stream/index.js:126)
    at Socket.<anonymous> (/home/me/prj/ssb/patchwork/node_modules/stream-to-pull-stream/index.js:143)
console.error @ base.html:19
base.html:19 Error: unexpected end of parent stream
    at PacketStream.destroy (/home/me/prj/ssb/patchwork/node_modules/packet-stream/index.js:71)
    at PacketStream.write (/home/me/prj/ssb/patchwork/node_modules/packet-stream/index.js:133)
    at /home/me/prj/ssb/patchwork/node_modules/muxrpc/pull-weird.js:58
    at /home/me/prj/ssb/patchwork/node_modules/pull-stream/sinks/drain.js:20
    at /home/me/prj/ssb/patchwork/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17
    at Object.cb (/home/me/prj/ssb/patchwork/node_modules/packet-stream-codec/index.js:98)
    at drain (/home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:46)
    at /home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:63
    at drain (/home/me/prj/ssb/patchwork/node_modules/stream-to-pull-stream/index.js:126)
    at Socket.<anonymous> (/home/me/prj/ssb/patchwork/node_modules/stream-to-pull-stream/index.js:143)
```
like 500ish times hehe

And I like the "View all gatherings" button in the Attending screen, could we have the opposite button in the All screen? And maybe in that case we don't need the new submenu in the More dropdown?

**Comment by christianbundy** [comment]
Could've sworn I already posted this somewhere, but:

@Powersource Could you specify which bits are breaking? To me, that looks like normal replication output that we see when a connection drops, but I don't want to merge this if it's actually breaking [new] things for you.

**Comment by Powersource** [comment]
The logs are maybe irrelevant but as mentioned I got infinite scuttling, which shouldn't happen.

**Comment by christianbundy** [comment]
Was that the same as #1184, or specific to this branch? I'm trying to juggle a bunch of bug input I've read across a few issues and a bunch of SSB threads, not sure which is relevant to which issue.

**Comment by Powersource** [comment]
Not sure, maybe.

**Comment by funwhilelost** [comment]
@christianbundy @Powersource fwiw I pulled this branch down, rebased it onto master at d8465c45, and fired it up.  Everything works great for me on Windows 10 and Ubuntu.  I love this feature. ❤️

**Comment by christianbundy** [comment]
Thanks for taking the time to review @funwhilelost, merging this now!

**Pull request merged**
