### PR TITLE
WIP: Add peer invites

### LINKED ISSUE #1059: Add ability to create & use peer-invites
Peer-invites as in https://github.com/ssbc/ssb-peer-invites

Asked @dominictarr and he said they're (mostly?) (any caveats? how's the pub support?) done. I'm thinking I'm gonna start working on this after my blob-summoning PR is done.

UX wise I'm thinking to add a button next to the Join pub button for creating invites, and turning the Join pub button into a generic Use invite button for both using pub invites and peer invites. The other option is to do like what we were doing with dht invites and create two new buttons next to the Join pub button, but I feel like we'd end up with a lot of buttons in the end and people wouldn't know which one to put their invite in. Thoughts on ux @mmckegg @cblgh ?

Any tips for how to test this in an easy way? I'm thinking I should maybe pack up my desktop computer and unfollow my laptop account, and then "rejoin" by inviting my desktop again. Would be nice to test with a fresh account though. Maybe I should just leave that part of the testing to someone else once the PR is up :P

### PR DESCRIPTION
**Pull request by Powersource**
Fixes https://github.com/ssbc/patchwork/issues/1059

todo:
* [ ] Remove console.logs
* [ ] All the other things

### CODE REVIEW

**Comment by Powersource** [comment]
@christianbundy something's up with the build here https://travis-ci.com/ssbc/patchwork/jobs/204252693

**Comment by christianbundy** [comment]
Yeah, Travis says their Windows VM is in "early access", which in my experience means "fails randomly about 5% of the time". In the past restarting the Windows job usually does the trick, I'll do that now and we'll see if that resolves it.

**Comment by christianbundy** [comment]
:tada:

**Comment by trosel** [comment]
Looking forward to this! Easy to invite friends directly. Much harder to explain to them how pubs work 😅

**Comment by Powersource** [comment]
Currently trying to get [this PR](https://github.com/ssbc/ssb-peer-invites/pull/22) merged.

**Comment by Powersource** [comment]
That PR is finally merged!

**Comment by christianbundy** [comment]
@Powersource Is this PR ready for review? I noticed it still has "WIP" in the title.

**Comment by Powersource** [comment]
Still very WIP (not that I'm working on it :p )

Jacob

**Comment by dominictarr** [comment]
was just checking to see if this was supported, hmm, currently patchbay is only front end client that supports peer-invites.

**Comment by arj03** [comment]
Wasn't there some money from the handshake grant for patchwork work or has that been used @Powersource ? If not I think this PR would be an ideal candidate. There are still a lot of users of patchwork.

**Comment by Powersource** [comment]
@arj03 No I think most of that money is still unused. I previously asked the others if I could do this and bill it but didn't get a response. I might just implement it and post an expense to the opencollective or something and see what happens :P

**Comment by arj03** [comment]
Yeah I mean there appears to be around 5k$ sitting in the [account](https://opencollective.com/patchwork#section-budget). And again I think it is a really good use of the money. Also some money should be allocated to the person reviewing this.

I feel a bit like an elephant barging in here, but it just seems to me that we should use the money we have for something at least ;-) 

Maybe bring this up on SSB to see what people feel? 

Personally if most of the new energy is in something like oasis, then I think it would make sense to allocate some of the funds towards making it easy to switch from patchwork (for one thing an easy installer). 

But again that is a whole different question. Also I think it maintenance of patchwork should be rewarded. Looking at the releases page I can see there are still regular releases.

Ping: @christianbundy

**Comment by christianbundy** [comment]
Yep, I'd really like to use the money but feel uncomfortable just writing a check to myself. I'd be comfortable funding some of this work on supporting peer invites, I think it's silly to just leave $5k in an account somewhere but we really don't have a process for spending it.

**Comment by black-puppydog** [comment]
I think the process is pretty much the same as it ever has been for #handshake-council, no? Write a small description on SSB, mention some folks on the council, get it approved, start work?

**Comment by christianbundy** [comment]
I think that was the case for the money managed directly by the council, but they sent money directly to the OpenCollective accounts for Patchwork, Patchbay, Patchfox, and Manyverse (I think) to spend directly on the project however they'd like. Cinnamon and Powersource and I agreed that we'd support each other and provide accountability, approving any expense as long as 2/3 of us were okay with it, but nobody has submitted an expense yet.

I think Patchbay is using the same hourly rate as the Sunrise Choir, $40/hr, maybe we support like 6 or 12 hours on peer invites and see what happens? I'd really like to spend some of the money fixing up dependencies, which will continue to be used long after Patchwork is gone, but I'd be comfortable starting with peer invites and would be excited to have them available in Patchwork.

**Comment by arj03** [comment]
I don't think you should feel bad about invoicing your own work. As I understand it from Jacob you have several people that will probably say something if it feels wierd. Especially considering you are also doing oasis.

**Comment by black-puppydog** [comment]
Yes I agree with @arj03 here. Those funds are specifically *for* doing the valuable work that is patchwork maintenance.

**Comment by Powersource** [comment]
Some progress, now you can create invites. But running into some bug when trying to open invites from someone else https://github.com/ssbc/ssb-peer-invites/issues/26

**Comment by Powersource** [comment]
Haven't dropped this, it's high on my todolist (but tbh I've procrastinated because I'm not looking forward to diving into the peer invite module code to debug this :p )

**Comment by Powersource** [comment]
Ok didn't get much further with the invite from browser-demo (see my new comment in the above issue for some questions)

Started another patchwork instance instead using the `--path` argument and tried to use an invite that I generated with my regular patchwork profile. But got this error which I recognize but don't know how to fix, any ideas? Buggy pub?

```
failed to use invite: {
  message: 'method:peerInvites,getInvite is not in list of allowed methods',
  name: 'Error',
  stack: 'Error: method:peerInvites,getInvite is not in list of allowed methods\n    '
```

**Comment by arj03** [comment]
I think to test this properly you should be very careful with what pubs get picked and maybe contact the owners to make sure all the plugins are updated. I remember a lot of them running old versions.

**Comment by Powersource** [comment]
Good point. I removed the servers from the invite and added yours instead (the only one I know is probably updated, know any others?).

Got a new error now! (gotta catch 'em all!)

```
failed to use invite: {
  message: 'while trying to connect ' +
    'to:net:between-two-worlds.dk:8989~shs:lbocEWqF2Fg6WMYLgmfYvqJlMfL7hiqVAV6ANjHWNw8=',
  name: 'Error',
  stack: 'Error: while trying to connect ' +
    'to:net:between-two-worlds.dk:8989~shs:lbocEWqF2Fg6WMYLgmfYvqJlMfL7hiqVAV6ANjHWNw8=\n' +
    '    at ' +
    '/home/me/prj/ssb/patchwork/node_modules/ssb-peer-invites/index.js:419:25\n' +
    '    at ' +
    '/home/me/prj/ssb/patchwork/node_modules/ssb-client/client.js:55:14\n  ' +
    'Error: could not connect to sbot\n    at ' +
    '/home/me/prj/ssb/patchwork/node_modules/ssb-client/client.js:55:17\n    ' +
    'at next ' +
    '(/home/me/prj/ssb/patchwork/node_modules/multiserver/compose.js:24:14)\n  ' +
    '  at /home/me/prj/ssb/patchwork/node_modules/multiserver/compose.js:34:9\n' +
    '    at _cb ' +
    '(/home/me/prj/ssb/patchwork/node_modules/multiserver/plugins/shs.js:28:20)\n' +
    '    at ' +
    '/home/me/prj/ssb/patchwork/node_modules/secret-handshake/protocol.js:118:22\n' +
    '    at ' +
    '/home/me/prj/ssb/patchwork/node_modules/pull-handshake/index.js:10:5\n    ' +
    'at /home/me/prj/ssb/patchwork/node_modules/pull-handshake/index.js:23:13\n' +
    '    at callback ' +
    '(/home/me/prj/ssb/patchwork/node_modules/pull-pushable/index.js:81:7)\n   ' +
    ' at drain ' +
    '(/home/me/prj/ssb/patchwork/node_modules/pull-pushable/index.js:68:39)\n  ' +
    'Error: shs.client: error when expecting server to accept challenge ' +
    '(phase 1).\npossibly the server is busy, does not speak shs or uses a ' +
    'different application cap\n    at abort ' +
    '(/home/me/prj/ssb/patchwork/node_modules/secret-handshake/protocol.js:37:45)\n' +
    '    at Object.cb ' +
    '(/home/me/prj/ssb/patchwork/node_modules/secret-handshake/protocol.js:44:24)\n' +
    '    at drain ' +
    '(/home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:43:23)\n  ' +
    'Error: stream ended with:0 but wanted:64\n    at drain ' +
    '(/home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:43:26)\n    ' +
    'at /home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:63:18\n   ' +
    ' at /home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:20:7\n   ' +
    ' at drain ' +
    '(/home/me/prj/ssb/patchwork/node_modules/stream-to-pull-stream/index.js:126:18)\n' +
    '    at Socket.<anonymous> ' +
    '(/home/me/prj/ssb/patchwork/node_modules/stream-to-pull-stream/index.js:143:5)\n' +
    '    at Socket.emit (events.js:205:15)\n    at endReadableNT ' +
    '(_stream_readable.js:1154:12)\n    at processTicksAndRejections ' +
    '(internal/process/task_queues.js:84:9)'
}
```

**Comment by arj03** [comment]
Hmm, why is it trying net? It should be using wss

**Comment by Powersource** [comment]
That's because I found `net:between-two-worlds.dk:8989~shs:lbocEWqF2Fg6WMYLgmfYvqJlMfL7hiqVAV6ANjHWNw8=` in my conn.json and thought that would work :P Since (in the other issue) there seemed to be problems with doing ws(s)

**Comment by Powersource** [comment]
And it's really weird, every time I run getNearbyPubs I think I get a list of the same 5 pubs, only 3 of which actually have willReplicate. One of the ones that won't replicate is your pub but it's always specified as its onion address, like why is my client even trying that haha (not like I'm even running tor)

**Comment by arj03** [comment]
Yeah I think it should be using the one assigned from ssb-device-address. I should probably change that for my pub :) I'll let you know in 5 minutes

**Comment by Powersource** [comment]
Woa I think it worked now! I added `//` so your address is `wss://between-two-worlds.dk:8989~shs:lbocEWqF2Fg6WMYLgmfYvqJlMfL7hiqVAV6ANjHWNw8=.ed25519`

**Comment by arj03** [comment]
Yep that address looks good :)

**Comment by arj03** [comment]
I should have updated my address now. The address format is a bit wierd, see: https://github.com/ssbc/multiserver/issues/58

**Comment by Powersource** [comment]
After wrestling with mutant a bit, things "should work", except that they don't appear to :P You can use an invite without getting an error, but it doesn't seem to publish the [`accept`](https://github.com/ssbc/ssb-peer-invites#peer-inviteaccept) nor `confirm` messages.

**Comment by Powersource** [comment]
Ok wow I was literally calling the wrong function. Anyway now I'm getting this

```
DEPRECATED gossip.add() was called. Use ssb-conn instead
Error: key must be ed25519 public id
    at validateAddr (/home/me/prj/ssb/patchwork/node_modules/ssb-conn/lib/gossip.js:54:15)
    at Object.Gossip.add (/home/me/prj/ssb/patchwork/node_modules/ssb-conn/lib/gossip.js:133:45)
    at Object.<anonymous> (/home/me/prj/ssb/patchwork/node_modules/secret-stack/util.js:80:17)
    at Object.<anonymous> (/home/me/prj/ssb/patchwork/node_modules/hoox/index.js:3:17)
    at Object.hooked [as add] (/home/me/prj/ssb/patchwork/node_modules/hoox/index.js:10:15)
    at /home/me/prj/ssb/patchwork/node_modules/ssb-peer-invites/index.js:506:27
    at Array.forEach (<anonymous>)
    at /home/me/prj/ssb/patchwork/node_modules/ssb-peer-invites/index.js:505:34
    at Object._requests.<computed> (/home/me/prj/ssb/patchwork/node_modules/packet-stream/index.js:38:5)
    at PacketStream._onrequest (/home/me/prj/ssb/patchwork/node_modules/packet-stream/index.js:151:26)
```

So I added the `//` before, does this part want me to remove it again? haha

**Comment by Powersource** [comment]
Had a `.ed25519` at the end of the invite from modifying it manually (browser-demo puts it there but patchwork doesn't, how does it still work in browser-demo?). So now it successfully `gossip.add`s! The server is in conn.json now however the connection seems to fail, I don't get any errors but the `failure` count in conn.json keeps going up.

And are you sure @arj03 that `wss:between-two-worlds.dk:8008~shs:lbocEWqF2Fg6WMYLgmfYvqJlMfL7hiqVAV6ANjHWNw8=` which is what you updated it to is right? When I try to connect to that port instead of 8989 I get this (with or without `//`)

```
WebSocket connection to 'wss://between-two-worlds.dk:8008/' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
```

**Comment by Powersource** [comment]
Oh shit the pub seems to have somehow published the confirm message! Now to figure out what I did to make it work hehe

**Comment by Powersource** [comment]
WOO IT WORKS

**Comment by Powersource** [comment]
Generated a new invite and saw that arj's server had a net: connection now, `net:between-two-worlds.dk:8008~shs:lbocEWqF2Fg6WMYLgmfYvqJlMfL7hiqVAV6ANjHWNw8=` so I just used that one and now I'm replicating and indexing like crazy :D

**Comment by Powersource** [comment]
Ok finished indexing. Some weird bugs now: I seem to have downloaded everything from the inviter (my regular @powersource account) and the people the inviter is following (if I go to their profiles/channels I can see everything like normal), but patchwork says that I'm not following @powersource and the Public feed is empty.

I'm gonna try to look around a bit to see if I can fix this, but this is more uncharted territory for me so input/help is welcome.

**Comment by Powersource** [comment]
Yeep if I run

```
      onceTrue(api.sbot.obs.connection, ssb => {
        ssb.friends.get({
          source: '@++IG2UtTTOatdHVvrbFsr7f8+MwrLN09jNheUQzkOoE=.ed25519', // my new profile
        }, (err, res) => {
          if (err) console.error('fr', err)

          console.log('friends res:', res)
        })
      })
```

I get

```
friends res: { '@Vz6v3xKpzViiTM/GAe+hKkACZSqrErQQZgv4iqQxEn8=.ed25519': true } // my regular profile
```

so it probably has something to do with patchwork's custom friend graph code, the index `patchwork-contacts` or the like.

**Comment by Powersource** [comment]
I tried

```diff
diff --git a/lib/plugins/contacts.js b/lib/plugins/contacts.js
index 147c061b..d0fe78eb 100644
--- a/lib/plugins/contacts.js
+++ b/lib/plugins/contacts.js
@@ -54,15 +54,10 @@ exports.init = function (ssb) {
     raw: view,
 
     isFollowing: function ({ source, dest }, cb) {
-      if (values && values[source]) {
-        cb(null, values[source][dest] === true)
-      } else {
-        view.get((err, graph) => {
-          if (err) return cb(err)
-          const following = graph && graph[source] && graph[source][dest] === true
-          cb(null, following)
-        })
-      }
+      ssb.friends.get({ source, dest }, (err, res) => {
+        if (err) return cb(err)
+        cb(null, res === true)
+      })
     },
 
     isBlocking: function ({ source, dest }, cb) {
```

and now I can see my regular profile in the Public feed (just like I'm following it), but patchwork still says the profiles aren't following each other, this implementation is really weird hehe.

I would like to use that same logic (`friends.get`) a bit earlier in the process, I have a feeling that might work. Here, to be specific https://github.com/ssbc/patchwork/blob/master/lib/plugins/contacts.js#L39 But FlumeReduce only seems to let that map function be sync and `friends.get` is async. Anyone got a good idea for a workaround? I'd rather not reim

---

ok so I might have tried to reimplement it. however, it doesn't work :( The index seems to look exactly like it usually does. now I'm going to bed. probably going to need help with this before I can continue

```diff
diff --git a/lib/plugins/contacts.js b/lib/plugins/contacts.js
index 147c061b..1c252bc3 100644
--- a/lib/plugins/contacts.js
+++ b/lib/plugins/contacts.js
@@ -18,11 +18,32 @@ exports.init = function (ssb) {
   const view = ssb._flumeUse('patchwork-contacts', FlumeReduce(0, function reduce (result, item) {
     // used by the reducer view
     if (!result) result = {}
+
+    if (item.invites && item.accepts) {
+      // code doesn't get here, why?!
+      // once we get here, we might have to also save item.invites and item.accepts into result
+
+      for (const guest in item.accepts) {
+        const inviter = item.invites[item.accepts[guest]]
+
+        if (inviter) {
+          if (!result[inviter]) result[inviter] = {}
+          if (!result[guest]) result[guest] = {}
+
+          // only consume invites once. probably better to also check confirm messages but we should just switch to using ssb-friends properly for that
+          if (!result[inviter][guest]) result[inviter][guest] = true
+          if (!result[guest][inviter]) result[guest][inviter] = true
+        }
+      }
+    }
+
     if (item) {
       for (const author in item) {
-        for (const contact in item[author]) {
-          if (!result[author]) result[author] = {}
-          result[author][contact] = item[author][contact]
+        if (author !== 'invites' && author !== 'accepts') {
+          for (const contact in item[author]) {
+            if (!result[author]) result[author] = {}
+            result[author][contact] = item[author][contact]
+          }
         }
       }
     }
@@ -33,10 +54,26 @@ exports.init = function (ssb) {
     return result
   }, function map (msg) {
     // used by the reducer view
-    if (msg.value && msg.value.content && msg.value.content.type === 'contact' && ref.isFeed(msg.value.content.contact)) {
-      return {
-        [msg.value.author]: {
-          [msg.value.content.contact]: getContactState(msg.value.content)
+    if (msg.value && msg.value.content) {
+      const type = msg.value.content.type
+
+      if (type === 'contact' && ref.isFeed(msg.value.content.contact)) {
+        return {
+          [msg.value.author]: {
+            [msg.value.content.contact]: getContactState(msg.value.content)
+          }
+        }
+      } else if (type === 'peer-invite') {
+        return {
+          invites: {
+            [msg.value.key]: msg.value.author
+          }
+        }
+      } else if (type === 'peer-invite/accept') {
+        return {
+          accepts: {
+            [msg.value.author]: msg.value.content.receipt
+          }
         }
       }
     }
```

**Comment by arj03** [comment]
Hey @Powersource, that is great news!

The invite functionality in browser is hacked a bit because I didn't want to port over all the stuff. So that's probably why it works in the browser but the invite is invalid in other clients. Can you send me one generated from both?

Great to hear that it helped with the device-address I added to my pub. Would probably be good with a list of what is needed from pub admins so we can get others to upgrade.

@christianbundy might be more familiar with how the contacts is working in patchwork. I havn't looked.

**Comment by black-puppydog** [comment]
I'm a bit confused here... peer invites and DHT invites are the same, right?
So this PR would add the capability to *create* these invites, while #1246 would only allow them to be accepted. Is that correct?

**Comment by Powersource** [comment]
No they're pretty different. Their repos are https://gitlab.com/staltz/ssb-dht-invite and https://github.com/ssbc/ssb-peer-invites if you want to read more.

**Comment by Powersource** [comment]
Gonna highlight this a bit more

> probably going to need help with this before I can continue

I'd love to pair program a bit on this with someone who feels comfortable-ish with developing for flume and/or patchwork.

**Comment by black-puppydog** [comment]
Thank you @Powersource for clarifying that. I don't know how I missed this. I guess I conflated the two from the very beginning. Very much not qualified to pair up on this though, sorry :(

**Comment by christianbundy** [comment]
Can we find some time to pair on this? My brain works between like 09:00 and 15:00 Pacific time. [Maybe helpful](https://time.is/PT). I'm pretty comfortable with FlumeDB but I don't think anyone understands Patchwork.

**Comment by elavoie** [comment]
> I think that was the case for the money managed directly by the council, but they sent money directly to the OpenCollective accounts for Patchwork, Patchbay, Patchfox, and Manyverse (I think) to spend directly on the project however they'd like. Cinnamon and Powersource and I agreed that we'd support each other and provide accountability, approving any expense as long as 2/3 of us were okay with it, but nobody has submitted an expense yet.
> 
> I think Patchbay is using the same hourly rate as the Sunrise Choir, $40/hr, maybe we support like 6 or 12 hours on peer invites and see what happens? I'd really like to spend some of the money fixing up dependencies, which will continue to be used long after Patchwork is gone, but I'd be comfortable starting with peer invites and would be excited to have them available in Patchwork.

I will let you guys figure the technical stuff. 

Regarding the governance of Patchwork funding, you guys have all a go from me to spend it. I took the initiative of asking for a Patchwork Open Collective, hoping this could allow the the Handshake Council to focus on other things, but it seems this required a little more help on the governance side of things. 

You can also write checks to yourselves, all of you are long time community members with plenty of trust. 40$/h seems fine to me and we can combine that with some funds from the [SSBC](https://opencollective.com/secure-scuttlebutt-consortium). If you guys aim for 10h/month of funded work (400$/month) coming 50/50 from SSBC (200$/month) and Patchwork (200$/month), we can support that for at least a year. We can also discuss with Mix to cover more funding from [Scuttlebutt Maintenance](https://opencollective.com/scuttlebutt-maintenance) if 10h/month is not enough to clear up the backlog.

**Comment by elavoie** [comment]
Just to clarify the intention of why getting the SSBC involved: I am trying to establish *sustainable flows* of money. Currently our only sustainable source is the 200$/month that comes in recurrent donation in the SSBC. We need to spend these regularly enough to show backers that their money is necessary and useful. This way this will incentivize more backers to support SSB in general, and their preferred clients in particular.

Still being the most used client, Patchwork maintenance seems like a prime candidate for leveraging recurrent funds and bootstrapping a maintenance team. My current thinking along these lines is to fund those that review and merge PRs (and therefore take responsibility of the quality of the code base), and encourage more volunteers to fix the easy and low-hanging fruits. I can create a separate issue to discuss governance, maintenance, and funding if you guys want to discuss this in more detail.

**Comment by Powersource** [comment]
@christianbundy Thanks! Will write to you on signal

@elavoie I like all of these words that you're writing, yeah let's keep discussing this in a new issue :)

**Comment by Powersource** [comment]
Had a call with Christian and we got a bit further

```diff
diff --git a/lib/plugins/contacts.js b/lib/plugins/contacts.js
index 147c061b..796cfb4a 100644
--- a/lib/plugins/contacts.js
+++ b/lib/plugins/contacts.js
@@ -18,11 +18,44 @@ exports.init = function (ssb) {
   const view = ssb._flumeUse('patchwork-contacts', FlumeReduce(0, function reduce (result, item) {
     // used by the reducer view
     if (!result) result = {}
+
+    for (const inviteMsgKey in item.invites) {
+      if (!result.invites) result.invites = {}
+      if (!result.invites[inviteMsgKey]) result.invites[inviteMsgKey] = item.invites[inviteMsgKey]
+    }
+
+    for (const invited in item.accepts) {
+      if (!result.accepts) result.accepts = {}
+      if (!result.accepts[invited]) result.accepts[invited] = item.accepts[invited]
+    }
+
+    if (result.invites && result.accepts) {
+      for (const guest in result.accepts) {
+        const inviteMsgKey = result.accepts[guest]
+        const inviter = result.invites[inviteMsgKey]
+
+        if (inviter) {
+          if (!result[inviter]) result[inviter] = {}
+          if (!result[guest]) result[guest] = {}
+
+          if (!result[inviter][guest]) result[inviter][guest] = true
+          if (!result[guest][inviter]) result[guest][inviter] = true
+
+          // todo: uncomment this so invites can only be consumed once
+          // should maybe also check for confirm message from a pub
+          // delete result.invites[inviteMsgKey][inviter]
+          // delete result.accepts[guest][inviteMsgKey]
+        }
+      }
+    }
+
     if (item) {
       for (const author in item) {
-        for (const contact in item[author]) {
-          if (!result[author]) result[author] = {}
-          result[author][contact] = item[author][contact]
+        if (author !== 'invites' && author !== 'accepts') {
+          for (const contact in item[author]) {
+            if (!result[author]) result[author] = {}
+            result[author][contact] = item[author][contact]
+          }
         }
       }
     }
@@ -33,10 +66,26 @@ exports.init = function (ssb) {
     return result
   }, function map (msg) {
     // used by the reducer view
-    if (msg.value && msg.value.content && msg.value.content.type === 'contact' && ref.isFeed(msg.value.content.contact)) {
-      return {
-        [msg.value.author]: {
-          [msg.value.content.contact]: getContactState(msg.value.content)
+    if (msg.value && msg.value.content) {
+      const type = msg.value.content.type
+
+      if (type === 'contact' && ref.isFeed(msg.value.content.contact)) {
+        return {
+          [msg.value.author]: {
+            [msg.value.content.contact]: getContactState(msg.value.content)
+          }
+        }
+      } else if (type === 'peer-invite') {
+        return {
+          invites: {
+            [msg.key]: msg.value.author
+          }
+        }
+      } else if (type === 'peer-invite/accept') {
+        return {
+          accepts: {
+            [msg.value.author]: msg.value.content.receipt
+          }
         }
       }
     }
```

but now I'm in the same state that I described before when I tried `friends.get`

> and now I can see my regular profile in the Public feed (just like I'm following it), but patchwork still says the profiles aren't following each other,

and I don't know if it did this before (I don't think so) but now I'm gossiping with more than the pub that invited me.

I think now the other files `lib/depject/profile/obs/contact.js` and/or `lib/depject/contact/obs.js` might be playing into it? Or there's just more to do in that same file?

Leaning towards dropping this project now, we'll see, even if I think this still is very important.

**Comment by Powersource** [comment]
So I'm un-committing from this work now (i.e. could technically work more on this, but no promises from now on).

Ways forward for anyone picking this up:
* Finish the diffs I've posted here (i.e. continue modifying patchwork's custom contact/friend logic). Probably the "simplest" solution in that it would take the least amount of lines of code written, but you'd need to be a bit lucky to figure out exactly which those lines would be.
* Get rid of the custom patchwork contact/friend logic and just use plain ssb-friends. I think we'd need to do https://github.com/ssbc/ssb-friends/issues/43 (can probably find that logic in manyverse). Plus all the work of replacing patchwork-contacts which would probably be a bunch of work and should be done in another PR. This solution is probably the cleanest, but would take a bunch of work, and there's no guarantee you won't run into other exotic patchwork bugs in the process (in fact this is likely to happen).
* Make the invited person publish a follow message on invite accept, and the inviter publish a follow message when they see who has accepted the invite. This solution might be the "easiest" solution since we would know sort of what to do and would hopefully not be too much work, but would be very hacky, probably buggy, suboptimal, and would still include diving into weird patchwork code.

---

Doing some math based on [this comment](https://github.com/ssbc/patchwork/pull/1068#issuecomment-589708245):

I've clocked 11 hours (that's pretty heavily rounded down from the actual hours but I'm fine with not counting the extra ones)

11 * $40 = $440 USD

Submitted an invoice here https://opencollective.com/patchwork/expenses/17418

**Pull request closed without merging**
