### PR TITLE
Add gpl-3 license

### PR DESCRIPTION
**Pull request by pfraze**
Based on the suggestions we've collected, I propose we merge this GPL3 license. If we find this is overly restrictive, we can alter the copyright in the future.

### CODE REVIEW

**Comment by clehner** [comment]
:heavy_check_mark:

**Comment by mixmix** [comment]
huh, interesting https://github.com/ssbc/patchwork/pull/227 has been merge but not this.

**Comment by mixmix** [comment]
@pfraze freshened this up

**Comment by pfraze** [comment]
cool. Let's go ahead with this

**Pull request merged**
