### PR TITLE
Add SSB URI support

### PR DESCRIPTION
**Pull request by christianbundy**
This adds support for the `ssb:` URI scheme in the search box as well as
message links via `navigate()`. The legacy URI parser (`require('url')`)
was also replaced with the WHATWG parser that ships with JavaScript,
which has accurate support for URIs that don't have hostnames.

---

See also: https://github.com/ssbc/patchbay/pull/306

### CODE REVIEW

**Comment by christianbundy** [comment]
Hey @mmckegg, is this something you'd be open to having merged?

**Comment by mmckegg** [comment]
@christianbundy Yep!

**Comment by christianbundy** [comment]
Sweet, is there anything you'd like to see changed before merging?

**Comment by mmckegg** [comment]
Code looks good, but I haven't tested it.

**Comment by christianbundy** [comment]
Sweet, I'll merge now -- the same code is running without issue in Patchbay, and from my testing it works great in Patchwork, so please ping me if it causes any trouble!

**Pull request merged**
