### PR TITLE
tracking pr to merge scuttlebot@10 (flume)

### PR DESCRIPTION
**Pull request by dominictarr**
flume isn't merged into scuttlebot yet, but I wanted to figure out what i'd need to change about patchwork to get it going. currently the main problem is these custom plugins. I'd be happier if it could run stock scuttlebot, if possible. If a plugin is really justified it should be published as it's own module.

in this current configuration, private messages don't work. What about decrypting them on the fly like patchbay does? (then a plugin isn't needed). Also, this design where the all private crypto is performed by patchwork will make it much more awkward to implement multiple identities.

The main thing to work out, though, is how this progress tracking code works. I'd like to make this part of the official scuttlebot api, rather than some custom hacks in patchwork. I currently don't understand how it works, though. I added some guards so that it keeps running if something is missing, and it seems to work!

Can someone (@mmckegg @ahdinosaur ?) explain how the progress stuff works? it looks like a combination of spinners and bars, but it's hard to see from looking at the code.

---

- [x] integrate new indexing progress into UI
- [x] extract [new patchcore sbot plugins](https://github.com/ssbc/patchcore/tree/backlinks-index/sbot-plugins) into their own packages
- [x] publish new patchcore major version

### CODE REVIEW

**Comment by dominictarr** [comment]
oh yeah, to run this, you'll need to link in scuttlebot at the flume branch. The practice that I find most convienient is to do another checkout for this branch (i.e. in a different directory) so that you don't have to be npm installing all the time.

**Comment by mixmix** [comment]
hey might be good for others to know what to do to get this stood up. I've been recently trying to move between a flume-sbot+patchbay and patchwork setup to do dev work.

Things I've done in updating and getting flume stood back up : 
- updated to node 7.10
- pulled latest scuttlebot/flume branch
- installed the latest secure-scuttlebutt and linked that into scuttlebot (on @ahdinosaur 's advice)
- install the scuttlebot and npm installed ssb-fulltext there, adding `    .use(require('ssb-fulltext'))` as line 52 (optional)
- backed up my .ssb folder : `cp -r ~/.ssb ~/.ssb-backup`
- wiped a bunch of folders
  ```
cd ~/.ssb
rm -rf node_modules private query fulltext0 flume
  ```
(wiping these may have been superstitious from past bad experiences)
- started sbot with `./bin.js server` and watched it fail repeatedly with error : 

```
Connected @6ilZq3kN0F+dXFHAPjAwMm87JEb/VdB+LC9eIMW3sa0=.ed25519
/home/mix/projects/SSBC/scuttlebot/plugins/replicate/legacy.js:322
      replicate({id: sbot.id, sequence: toSend[sbot.id] || 0})
                                              ^

TypeError: Cannot read property '@ye+QM09iPcDJD6YvQYjoQc7sLF/IFhmNbEqgdzQo3lQ=.ed25519' of undefined
    at fallback (/home/mix/projects/SSBC/scuttlebot/plugins/replicate/legacy.js:322:47)
    at EventEmitter.<anonymous> (/home/mix/projects/SSBC/scuttlebot/plugins/replicate/legacy.js:316:7)
    at emitTwo (events.js:111:20)
    at EventEmitter.emit (events.js:194:7)
    at setupRPC (/home/mix/projects/SSBC/scuttlebot/node_modules/secret-stack/index.js:165:13)
    at /home/mix/projects/SSBC/scuttlebot/node_modules/multiserver/compose.js:83:18
    at next (/home/mix/projects/SSBC/scuttlebot/node_modules/multiserver/compose.js:28:14)
    at /home/mix/projects/SSBC/scuttlebot/node_modules/multiserver/compose.js:33:9
    at _cb (/home/mix/projects/SSBC/scuttlebot/node_modules/multiserver/plugins/shs.js:31:11)
    at /home/mix/projects/SSBC/scuttlebot/node_modules/secret-handshake/protocol.js:120:7
```
- put sbot into an infinite wihle loop : `while true; do ./bin.js server; done` (because it did increment, but is still crashing a lot) ..... seems to be working, but the indexing is still underway

Context: I've been running flume branch for the last month (happily, super stable). yesterday I hit turbulence after opening patchwork.

**Comment by mixmix** [comment]
update - I got home and continued the indexing, and it seems that not having friends on the same wifi (art-hack) means no trouble. no crashes

**Comment by mixmix** [comment]
couple of other errors : 
```
Error: expected previous: %9IJnoIqImHKVEvDM48huoJOwA7OXT0LsudfCZIKj6t4=.sha256but found:%kIz3LcwUPMTfPPhwjYX3zy3cPampRfaRcVejICfih3M=.sha256
    at Object.exports.isInvalid (/home/mix/projects/SSBC/secure-scuttlebutt/node_modules/ssb-feed/util.js:130:14)
    at validate (/home/mix/projects/SSBC/secure-scuttlebutt/node_modules/ssb-feed/validator.js:71:14)
    at queue (/home/mix/projects/SSBC/secure-scuttlebutt/node_modules/ssb-feed/validator.js:97:5)
    at add (/home/mix/projects/SSBC/secure-scuttlebutt/node_modules/ssb-feed/validator.js:104:5)
    at next (/home/mix/projects/SSBC/secure-scuttlebutt/index.js:100:7)
    at EventEmitter.db.add (/home/mix/projects/SSBC/secure-scuttlebutt/index.js:97:24)
    at /home/mix/projects/SSBC/secure-scuttlebutt/index.js:143:12
    at /home/mix/projects/SSBC/secure-scuttlebutt/node_modules/pull-stream/throughs/async-map.js:28:13
    at /home/mix/projects/SSBC/scuttlebot/node_modules/pull-next/index.js:29:11
    at /home/mix/projects/SSBC/scuttlebot/node_modules/pull-stream/throughs/through.js:19:9
Error: expected previous: %bILRh9JhOUD2mSGHsbyPW33LqtDF/DJQf7Rsmh1ujbY=.sha256but found:%M5RvGU40efMyIf18+a6pTeob2mjyyF9VE53c7+GnlFw=.sha256
    at Object.exports.isInvalid (/home/mix/projects/SSBC/secure-scuttlebutt/node_modules/ssb-feed/util.js:130:14)
    at validate (/home/mix/projects/SSBC/secure-scuttlebutt/node_modules/ssb-feed/validator.js:71:14)
    at queue (/home/mix/projects/SSBC/secure-scuttlebutt/node_modules/ssb-feed/validator.js:97:5)
    at add (/home/mix/projects/SSBC/secure-scuttlebutt/node_modules/ssb-feed/validator.js:104:5)
    at next (/home/mix/projects/SSBC/secure-scuttlebutt/index.js:100:7)
    at EventEmitter.db.add (/home/mix/projects/SSBC/secure-scuttlebutt/index.js:97:24)
    at /home/mix/projects/SSBC/secure-scuttlebutt/index.js:143:12
    at /home/mix/projects/SSBC/secure-scuttlebutt/node_modules/pull-stream/throughs/async-map.js:28:13
    at /home/mix/projects/SSBC/scuttlebot/node_modules/pull-next/index.js:29:11
    at /home/mix/projects/SSBC/scuttlebot/node_modules/pull-stream/throughs/through.js:19:9
+++++++++++++++++++++++++++++++++++++++++++++++++++Error: expected previous: %OTjIjYo2NBvZyDEN4YPGswAJJKYmRb3OGwhUZSwSG5k=.sha256but found:%CEWihRy17rejlJFMw+Z/vscpr49XfqEE9FBXn00Y0Kw=.sha256
    at Object.exports.isInvalid (/home/mix/projects/SSBC/secure-scuttlebutt/node_modules/ssb-feed/util.js:130:14)
    at validate (/home/mix/projects/SSBC/secure-scuttlebutt/node_modules/ssb-feed/validator.js:71:14)
    at queue (/home/mix/projects/SSBC/secure-scuttlebutt/node_modules/ssb-feed/validator.js:97:5)
    at add (/home/mix/projects/SSBC/secure-scuttlebutt/node_modules/ssb-feed/validator.js:104:5)
    at next (/home/mix/projects/SSBC/secure-scuttlebutt/index.js:100:7)
    at EventEmitter.db.add (/home/mix/projects/SSBC/secure-scuttlebutt/index.js:97:24)
    at /home/mix/projects/SSBC/secure-scuttlebutt/index.js:143:12
    at /home/mix/projects/SSBC/secure-scuttlebutt/node_modules/pull-stream/throughs/async-map.js:28:13
    at /home/mix/projects/SSBC/scuttlebot/node_modules/pull-next/index.js:29:11
    at /home/mix/projects/SSBC/scuttlebot/node_modules/pull-stream/throughs/through.js:19:9
```

**Comment by mmckegg** [comment]
@dominictarr So, I just tried this out. Once I got up in running, seemed to work fine! (except for progress of course)

However, I noticed that this requires manually removing old indexes in order to upgrade to use flume. This isn't really something we can expect patchwork users to do (without this, nothing loads). How should we automate this? How can we ensure this doesn't break old patchwork versions or interfere with other installed scuttlebots? Can flume and legacy coexist in a single `~/.ssb`?

Not happy about merging until all of these questions have good answers.

**Comment by mmckegg** [comment]
### Re progress:

The current progress code doesn't matter too much. I wouldn't worry about compatibility.

What I would like out of scuttlebot is the following (maybe as a stream):

- number of pending messages to download
- a list of peers that are currently syncing, how many pending feeds left to sync
- number of messages left to index

**Comment by mmckegg** [comment]
From https://github.com/ssbc/scuttlebot/pull/407

> Okay, upon further investigation it appears I was wrong. Looks like scuttlebot@10 + plugins are fully compatible with older versions (no need to delete things from your `~/.ssb/`). Just takes ages to reindex. 
> 
> So, I guess all that patchwork needs is a progress bar and then everything would be perfect 😄 

Also need to handle the private index somehow.

**Comment by dominictarr** [comment]
@mmckegg the private index, yes. At least, it should change into a flume view. Could we move this into scuttlebot? I'd be happier if patchwork worked with stock sbot

**Comment by dominictarr** [comment]
Also, I have a _pet peeve_ about spinners, we have the capability to do progress bars that somewhat accurately reflect how much work there really is to be done, I'd be very happy if patchwork had that.

**Comment by mmckegg** [comment]
Yes, I'd like to handle the private index in patchwork. 

And totally agree about spinners. The one place they are good is indicating that more data is on its way. But if you know how much already, it should be a progress bar.

**Comment by mixmix** [comment]
Spinners are like Tarr kryptonite. Dominic do you have a repo like this one
of mine :
https://github.com/mixmix/blogposts/blob/master/DRAFT/knowing_your_rants.md

**Comment by dominictarr** [comment]
spinners are very bad for a ADHD type personality because they give no indication of how long this thing will take, so create an increased opportunity to become distracted

**Comment by mmckegg** [comment]
**My opinion:**
Spinners are perfect for things that are likely to take < 3 seconds. Like this, they make things feel more responsive. But outside of this, they do the opposite.

**Comment by mmckegg** [comment]
Okay, getting close now!

Need to split out my [new sbot plugins](https://github.com/ssbc/patchcore/tree/backlinks-index/sbot-plugins) into their own module. Then we need to bump major on patchcore to use the new indexes.

@mixmix we need to talk about patchbay and how this will affect it. Hopefully patchwork won't need it's own patchcore fork 😆

**Comment by mmckegg** [comment]
I also still need to integrate the new indexing progress into patchwork's UI

**Comment by mmckegg** [comment]
Okay, I'm gonna merge this! Still a few weird bugs (#555), but overall, it's getting really good!

**Pull request merged**
