### PR TITLE
Fix pull-resume pagination bug

### LINKED ISSUE #978: private tab is missing messages
Maybe a paging issue? 

Might also affect other views but harder to tell. It seems that most recent messages are there, but then there is a gap and after that is older messages.

cc @ahdinosaur

### PR DESCRIPTION
**Pull request by christianbundy**
The problem seems to be caused by the marker counter getting ahead of
the limit constrained by `pull.take()`. This moves both the filter and
the `pull.take()` before the marker counter, which ensures that if the
counters become out of sync the marker counter can only be behind --
never ahead.

Still unclear about why this changed between scuttlebot 12 and 13. :man_shrugging: 

Resolves #978

### CODE REVIEW

**Comment by christianbundy** [comment]
Hmm... this might not be working anymore (???).

**Comment by christianbundy** [comment]
Nevermind, I accidentally changed the order of the stream while debugging in my last commit -- I've amended the commit with the correct behavior, this is now good to go and seems to completely resolve the problem. :tada: 

Still concerned over why it broke in the first place...

**Comment by christianbundy** [comment]
Woo! Thanks for testing, I think this is the last bug before we're finally ready for a real release!

:tada: :tada: :tada:

**Comment by Powersource** [comment]
This one https://github.com/ssbc/patchwork/issues/1009 is marked as blocking tho

**Comment by christianbundy** [comment]
Yep, just waiting for them to confirm whether their problem is 100% resolved on Windows. They said:

> edit: after the forced reboot I ran the installer again and everything works

But they didn't close the issue, so I'm hesitant to close it and create a release.

**Comment by ThunderFD** [comment]
sorry for the delay, closed it now after trying to find info on the BSOD, but gave up^^

**Comment by christianbundy** [comment]
No problem at all, thanks a bunch!

**Comment by Powersource** [comment]
btw OMG I can scroll normally now :tears_of_joy: Did you update electron or something? It's buttery smooth now (as opposed to the previous molasses lol)

**Comment by christianbundy** [comment]
Check out #964! It's all @nornagon, I'm super happy with the upgrade.

**Comment by mmckegg** [comment]
Ya'll are doing awesome work! ❤️❤️❤️❤️❤️

**Pull request merged**
