### PR TITLE
update electron-prebuilt

### PR DESCRIPTION
**Pull request by dominictarr**
with this PR you can run patchwork with node@4

@kyledrake was hasseling me into making this easier to install and here we are

### CODE REVIEW

**Comment by pfraze** [comment]
This appears to work. Some breaking changes were made for electron between `0.28` and `0.33`, but I haven't com across any breaks in testing this. Let's be on the lookout.

Also, https://github.com/ssbc/docs/issues/9

**Comment by dominictarr** [comment]
did you publish this?

**Comment by pfraze** [comment]
not yet published

**Comment by dominictarr** [comment]
can we publish this then?

**Comment by pfraze** [comment]
Yeah I think it's good to go

**Comment by pfraze** [comment]
Published `1.0.3`

**Comment by dominictarr** [comment]
@kyledrake can you try reinstalling this and let us know if it works?

**Pull request merged**
