### PR TITLE
refactor: restyle to use reduced line length

### PR DESCRIPTION
**Pull request by christianbundy**
This restyles Patchwork to use a much smaller line length which is in
line with best practices regarding typography. This also includes a
change to the layout of the profile page so that elements have more room
to breathe as well as a change to the font-size and the margins of `<h1>`
through `<h6>` so that they don't have such a stark contrast with the rest
of the text rendered.

Resolves https://github.com/ssbc/patchwork/issues/1102

Screenshot from 2019-06-16 09-41-00
Screenshot from 2019-06-16 09-40-35
Screenshot from 2019-06-16 09-40-23
Screenshot from 2019-06-16 09-40-11
Screenshot from 2019-06-16 09-39-53
Screenshot from 2019-06-16 09-39-40
Screenshot from 2019-06-16 09-39-29

### CODE REVIEW

**Comment by christianbundy** [comment]
@black-puppydog I've tested this with 48rem instead of 42rem and I think it's a bit less extreme, do you think increasing the line length in the screenshots by 15% would make it feel less bare? Overall I think it's a ~30% reduction from the current line length.

**Comment by christianbundy** [comment]
Here are some screenshots of 48rem (576px, down from 800px):

Screenshot from 2019-06-18 08-37-39
Screenshot from 2019-06-18 08-36-21
Screenshot from 2019-06-18 08-35-38
Screenshot from 2019-06-17 09-16-10
Screenshot from 2019-06-17 09-15-54

**Comment by christianbundy** [comment]
Just pushed a commit to increase the line length up to 48, I'm hoping that's a reasonable compromise between skinny sausage-style feeds and thicc barge-style feed lengths. Maybe? I'd love for this to be configurable in the future. :+1:

**Comment by mmckegg** [comment]
Kind of like how it used to be.

You can't please everyone: https://github.com/ssbc/patchwork/pull/720

**Pull request closed without merging**
