### PR TITLE
bin start script

### PR DESCRIPTION
**Pull request by ahdinosaur**
https://github.com/ssbc/patchwork/issues/565#issuecomment-310051291

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
Just tried this, but I get the NODE_MODULE_VERSION mismatch error on start—copying + pasting + running the `rebuild` script from patchwork works, but it seems like it should be doing that automatically already in the postinstall script…

**Comment by hbetts** [comment]
I installed this branch globally myself, then ran `patchwork`, but nothing happened. It looked as if the terminal froze, though a quick `CTRL+c` exited the Node process successfully.

So I tried running `electron` directly, providing it the path to the `index.js` file, and I received the following:

```bash
Error: The module 'ssb-patchwork/node_modules/leveldown/build/Release/leveldown.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
```

Running `npm run rebuild` from within the `ssb-patchwork` module rebuilt the appropriate binaries, and I was able to run `patchwork` successfully.

@ahdinosaur any ideas why this PR isn't working out of the box without the manual `npm run rebuild` step?

**Comment by ahdinosaur** [comment]
> @ahdinosaur any ideas why this PR isn't working out of the box without the manual npm run rebuild step?

@hbetts i have no idea!

i rebased this branch to the latest master, since the recent prebuild updates might fix our native build problem.

however i'm getting this error:

```
Error: ENOENT: no such file or directory, scandir '/home/dinosaur/.nvm/versions/node/v8.2.1/lib/locales'
    at Object.fs.readdirSync (fs.js:910:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:575:28)
    at guessLocales (/home/dinosaur/.nvm/versions/node/v8.2.1/lib/node_modules/ssb-patchwork/node_modules/i18n/i18n.js:618:22)
    at Object.i18nConfigure [as configure] (/home/dinosaur/.nvm/versions/node/v8.2.1/lib/node_modules/ssb-patchwork/node_modules/i18n/i18n.js:151:34)
    at _init (/home/dinosaur/.nvm/versions/node/v8.2.1/lib/node_modules/ssb-patchwork/plugs/intl/sync/i18n.js:89:11)
    at i18n (/home/dinosaur/.nvm/versions/node/v8.2.1/lib/node_modules/ssb-patchwork/plugs/intl/sync/i18n.js:55:5)
    at /home/dinosaur/.nvm/versions/node/v8.2.1/lib/node_modules/ssb-patchwork/node_modules/depject/apply.js:18:30
    at page (/home/dinosaur/.nvm/versions/node/v8.2.1/lib/node_modules/ssb-patchwork/modules/page/html/render/public.js:66:71)
    at /home/dinosaur/.nvm/versions/node/v8.2.1/lib/node_modules/ssb-patchwork/node_modules/depject/apply.js:18:30
    at defaultViews.forEach (/home/dinosaur/.nvm/versions/node/v8.2.1/lib/node_modules/ssb-patchwork/modules/app/views.js:15:25)
```

**Comment by hbetts** [comment]
Even with the rebased branch I'm still not having any luck running the `index.js` file using `electron`.

I didn't encounter the `locales` error.

I'm sorry for not being helpful here.

**Pull request closed without merging**
