### PR TITLE
wip: build for Raspberry Pi (arm32v7) on Travis

### PR DESCRIPTION
**Pull request by ahdinosaur**
fixes: https://github.com/ssbc/patchwork/issues/1069

### CODE REVIEW

**Comment by ahdinosaur** [comment]
am stuck on an error on Travis that matches when i run this locally:

```
> @felixrieseberg/spellchecker@4.0.8 install /app/node_modules/@felixrieseberg/spellchecker
> node-gyp rebuild
qemu: Unsupported syscall: 397
qemu: Unsupported syscall: 397
gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-1028-gcp
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/@felixrieseberg/spellchecker
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @felixrieseberg/spellchecker@4.0.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @felixrieseberg/spellchecker@4.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-02T03_30_36_997Z-debug.log
```

complete log on my local machine doesn't say anything more useful.

**Comment by ahdinosaur** [comment]
here's the most similar issue i could find: https://github.com/agalwood/Motrix/issues/283, but there the response is that it's a native dependency issue.

i also got more logs by calling `node-gyp rebuild` directly, but still nothing that says what's wrong:

```
node@da89b8cc3af6:~/app/node_modules/@felixrieseberg/spellchecker$ "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" rebuild -v   
qemu: Unsupported syscall: 397
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '-v' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | linux | arm
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.9
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.16.0
gyp verb command install [ '10.16.0' ]
gyp verb install input version string "10.16.0"
gyp verb install installing version: 10.16.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.16.0
gyp verb build dir attempting to create "build" dir: /home/node/app/node_modules/@felixrieseberg/spellchecker/build
gyp verb build dir "build" dir needed to be created? /home/node/app/node_modules/@felixrieseberg/spellchecker/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/node/app/node_modules/@felixrieseberg/spellchecker/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/node/app/node_modules/@felixrieseberg/spellchecker/config.gypi
gyp verb common.gypi checking for gypi file: /home/node/app/node_modules/@felixrieseberg/spellchecker/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/node/app/node_modules/@felixrieseberg/spellchecker/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/node/.node-gyp/10.16.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/node/.node-gyp/10.16.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/node/.node-gyp/10.16.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/node/app/node_modules/@felixrieseberg/spellchecker',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
qemu: Unsupported syscall: 397
gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.9.0-8-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "-v"
gyp ERR! cwd /home/node/app/node_modules/@felixrieseberg/spellchecker
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
```

**Comment by ahdinosaur** [comment]
since the only information is the unsupported qemu syscall, looking at https://fedora.juszkiewicz.com.pl/syscalls.html, it's http://www.man7.org/linux/man-pages/man2/statx.2.html.

there's heaps of other `qemu: Unsupported syscall:` lines that happen, so i didn't think much of it. but i'm already using the latest Ubuntu provided by TravisCI, so not sure how to approach this.

maybe i'm doing something wrong with qemu, as it worked great for me in the past to do cross-compilation of native node modules.

**Comment by ahdinosaur** [comment]
nevermind, resolved the problem by using https://github.com/hypriot/qemu-register. :cake:

**Comment by christianbundy** [comment]
@ahdinosaur Is this still in progress?

**Comment by ahdinosaur** [comment]
@christianbundy yes, in that i think Raspberry Pi support is a good thing to do, and i never finished this. but no, in that i don't plan to come back to this right now.

**Comment by christianbundy** [comment]
Cool, I'll assign it to you so that the stale[bot] doesn't do anything -- feel free to close if you'd like.

**Comment by christianbundy** [comment]
Sorry to change my mind, but I realized that since all of these PRs are outdated I've been ignoring the PR count and missed some new PRs. I'm going to close this for now, please re-open if you have the time / interest / energy to work on this again! :heart:

**Pull request closed without merging**
