### PR TITLE
Update har-validator

### LINKED ISSUE #897: Dependency issue with har-validator 5.1.2
Hello,

I tried to build patchwork from the master branch using the § build from source section of the README. Please excuse me in advance for inaccuracies here, this is first time I use npm, or a real javascript project.

The `npm install` command fails with the following error:

    npm ERR! 404 Not Found: har-validator@5.1.2

The `har-validator` package is a dependency of `request`, which is a dependency of `nugget`, which is a dependency of `electron-download`, itself a dependency of `electron` ; so I am not even sure this is the right Github project to open an issue on. Anyway, the version 5.1.2 doesn't exist according to npm registry. The closet existing versions are [5.1.0](https://registry.npmjs.org/har-validator/5.1.0) and [5.1.3](https://registry.npmjs.org/har-validator/5.1.3).

What can I do ?

### PR DESCRIPTION
**Pull request by christianbundy**
har-validator@5.1.2 was unpublished, so this commit manually updates itto 5.1.3 to resolve an installation issue with the missing dependency.

Resolves #897 

cc: @Aversiste can you confirm that this resolves the issue for you?

### CODE REVIEW

**Comment by Aversiste** [comment]
The install process doesn't fail at this step anymore which is definitely a progress. Thanks !

**Comment by christianbundy** [comment]
Sweet. This looks like a trivial fix that's breaking the build so I'll merge now.

**Comment by neftaly** [comment]
@christianbundy looks like a regression was made in b947e385 - can you please re-do this PR?

**Comment by christianbundy** [comment]
@neftaly Could you open a new issue with more information on what's going on? I've pulled the latest `master` and both `npm ci` and `npm install` seem to be working for me.

**Pull request merged**
