### PR TITLE
Channel subscription and AllChannels CSS changes

### LINKED ISSUE #879: Channel CSS Light Theme Missing Subscribed Green Left Boarder CSS
Not sure if this is intended, but in switching back from the Dark theme to the Light theme I noticed that the Left Boarder of the Channel name Box.

Dark CSS For subscribed Channels
```
.AllChannels > a.channel.-subscribed {
    background-image: url(data:image/svg+xml;charset=utf-8;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5…c1JyAvPiA8Y2lyY2xlIGN4PSc2JyBjeT0nNicgcj0nMycgZmlsbD0nIzg4OCcvPjwvc3ZnPg==);
    border-top-left-radius: 0px;
    border-bottom-left-radius: 0px;
    border-left: 2px solid rgb(81, 192, 103);
}
```

Light CS
```
.AllChannels > a.channel.-subscribed {
    background-image: url(data:image/svg+xml;charset=utf-8;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5…c1JyAvPiA8Y2lyY2xlIGN4PSc2JyBjeT0nNicgcj0nMycgZmlsbD0nIzg4OCcvPjwvc3ZnPg==);
}
```

Not sure if intended but the light theme is missing a few CSS elements for subscribed channels.

### PR DESCRIPTION
**Pull request by kroppt**
- Add green bar on light theme, fixes  #879 
- Made the circle icon (represents being subscribed) not go away upon hover
- Unsubscribe button changes to red (complementary color to subscribe button's green)
- Made sure unsubscribe button icon transitions correctly on dark and has same color as text

### CODE REVIEW

**Comment by christianbundy** [comment]
Hey, thanks for putting this together! I've attached some screenshots below, which are really helpful in this sort of thing.

- :heavy_check_mark: Confirmed resolves #879, great work!
- :heavy_multiplication_x:  The circle icon is still going away on hover for me, am I testing it wrong?
- :grey_question:  I think the button should maybe say "Unsubscribe" if it's going to be red, what do you think?
- :heavy_check_mark: No problems with the button color transition as far as I could see.

## Before

subscribed-channel
unsubscribe-default

## After

hover-circle-missing
unsubscribe

**Comment by kroppt** [comment]
>  * heavy_multiplication_x  The circle icon is still going away on hover for me, am I testing it wrong?

No, that is my mistake. I forgot about the channel list on the left there. I hadn't subscribed to anything on that list, so I forgot to test it.

>  * grey_question  I think the button should maybe say "Unsubscribe" if it's going to be red, what do you think?

I think that makes sense. It's a button, so it should have an action on it.

I'll get to work on this stuff.

**Comment by kroppt** [comment]
@christianbundy 
Give it another go. The translation appeared to already be complete for "Unsubscribe."

**Comment by christianbundy** [comment]
Looks great to me, in both the light and dark themes. Thanks for the quick fixes! I'm going to merge this and let it bake in `master` before the next release.

**Pull request merged**
