### PR TITLE
Notifications dropdown

### PR DESCRIPTION
**Pull request by pfraze**
Replaces the notifications view with a persistent icon, top right, that opens a dropdown 

screen shot 2015-11-29 at 9 20 34 pm
screen shot 2015-11-29 at 9 20 44 pm
screen shot 2015-11-29 at 9 46 39 pm
screen shot 2015-11-29 at 9 46 51 pm

### CODE REVIEW

**Comment by pfraze** [comment]
RFR @dominictarr @mixmix

**Comment by pfraze** [comment]
per #135

**Comment by mixmix** [comment]
yeah I like that. 
I think it works as long as there's an easy way to see what the makeup of new notifications is. 
e.g. 

---

All   |  **Likes** (5) |   **Follows** (1)  | Mentions

---

Sure there could be some design around that, but text might be a start...

**Comment by mixmix** [comment]
I really really like notifications being out of the content bar on the left. Notifications are like extras IMO

**Pull request merged**
