### PR TITLE
update scuttlebot to v9

### PR DESCRIPTION
**Pull request by dominictarr**
this removes the plugin plugin - it was mostly awkward. I think it would be easier to use by creating a custom distribution that wraps sbot, like the way patchwork does it.

Also, it incorporates some performance improvements on replication, shifts to using multiserver internally,
and most interestingly now supports pubs running on tor. (thanks to @arj03)

### CODE REVIEW

**Comment by arj03** [comment]
@dominictarr this means that all addresses now are multiserver? Meaning starts with net: or onion:?

On my onion pub I saw that as soon as it got connection with my sbot, it started contacting and getting messages for a lot of other pubs. Which in my case is fine (I don't care about anonymity), but as you also talked about, we probably need some kind of mode no enable multiserver plugins. Meaning that if you only want sbot to do tor, you would only enable the onion plugin. What are your thoughts on that?

**Comment by dominictarr** [comment]
oops, I messed that up - make sure you have scuttlebot@9.0.1.
9.0.0 didn't actually used multiserver.
correct all the things that took an address, such as `gossip.connect` now support multiserver addresses.
They also work with old `ip:port:key` addresses.

It would be a pretty simple change to the `scuttlebot/plugins/gossip` to have a config setting to only connect to `.onion` pubs. then you'd have that.

We need to rewrite the `gossip` plugin.
Firstly, it doesn't remember what servers are good inbetween runs, which means it has to reconnect to them all - just to see which onces actually work. That means it tries to replicate with each one,
which is alot of kb just to figure out that nothing has happened.

I also want to move towards connection tunneling - I should be able to connect to you, by tunneling through one (or more) pubs. then can bootstrap a direct p2p connection...

**Comment by arj03** [comment]
I see, makes sense.

**Comment by arj03** [comment]
I have upgraded to sbot 9.0.1 on my pub and furthermore upgraded patchwork to also run sbot 9, meaning I'm now running without any of my patches and I don't get a connection. Not sure why, it's like its not even trying to connect. Can I force it to connect somehow?

**Comment by dominictarr** [comment]
make sure you have secret-stack@3 in the dependency tree,
there are lots of pubs, so you will need to tell it to connect.

do `sbot gossip.connect onion:{host}:{port}~shs:{key}`
I never successfully connected to your pub via tor, but I did to @cryptix's

**Comment by arj03** [comment]
My pub was suffering from extremely high/memory cpu usage, so it was killed constantly, thats probably why you havn't been able to connect. Seems to be the same problem keks is seeing.

Anyway, testing some more. I think we need this patch:

https://github.com/ssbc/ssb-ref/pull/8

Then I need this change:

https://github.com/ssbc/secret-stack/pull/10#issuecomment-250833200

Otherwise it won't try the onion plugin. And lastly the onion plugin server will fail when starting a server with:
```

/home/arj/.nvm/versions/node/v6.1.0/lib/node_modules/scuttlebot/node_modules/socks/lib/socks-client.js:196
                    buff.writeUInt8(options.target.host.length);
                                                       ^

TypeError: Cannot read property 'length' of undefined
    at sendRequest (/home/arj/.nvm/versions/node/v6.1.0/lib/node_modules/scuttlebot/node_modules/socks/lib/socks-client.js:196:56)
    at Socket.authenticationResponse (/home/arj/.nvm/versions/node/v6.1.0/lib/node_modules/scuttlebot/node_modules/socks/lib/socks-client.js:174:25)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)

```
But we don't really need the server as I see it because we listen on localhost.

With all of this I get challenge not accepted with:

 sbot gossip.connect onion:355ij5sv346bpih2.onion:8008~shs:lbocEWqF2Fg6WMYLgmfYvqJlMfL7hiqVAV6ANjHWNw8=

A bit wierd, it was working before.

**Comment by dominictarr** [comment]
what version are you running? can you post your dep tree with `npm ls`?

**Comment by arj03** [comment]
I'm now running sbot 9.0.1 with my ssb-ref patch and the changes described above.

On the server I'm running sbot 9.0.1 with my ssb-ref patch only. The pub server is running now if you need test :)

npm ls locally for sbot:

├─┬ scuttlebot@9.0.1
│ ├── bash-color@0.0.4
│ ├── broadcast-stream@0.0.0
│ ├─┬ cont@1.0.3
│ │ ├── continuable@1.2.0
│ │ ├─┬ continuable-para@1.2.0
│ │ │ ├─┬ continuable-hash@0.1.4
│ │ │ │ └── continuable@1.1.8
│ │ │ └─┬ continuable-list@0.1.6
│ │ │   └── continuable@1.1.8
│ │ └── continuable-series@1.2.0
│ ├── explain-error@1.0.3
│ ├── graphmitter@1.6.3
│ ├── ip@0.3.3
│ ├─┬ level-memview@0.0.0
│ │ ├─┬ level-live-stream@1.4.11
│ │ │ ├─┬ level-sublevel@6.3.17
│ │ │ │ ├─┬ bytewise@0.7.1
│ │ │ │ │ └─┬ bops@0.1.1
│ │ │ │ │   ├── base64-js@0.0.2
│ │ │ │ │   └── to-utf8@0.0.1
│ │ │ │ └── pull-stream@2.21.0
│ │ │ ├── pull-level@1.5.2
│ │ │ └─┬ pull-stream-to-stream@1.2.6
│ │ │   └── pull-core@1.0.0
│ │ ├─┬ pull-level@1.2.0
│ │ │ ├─┬ pull-pushable@1.1.4
│ │ │ │ └── pull-stream@2.18.3
│ │ │ └── stream-to-pull-stream@1.3.1
│ │ └─┬ pull-stream@2.26.1
│ │   └── pull-core@1.1.0
│ ├─┬ mdmanifest@1.0.8
│ │ ├─┬ remark@3.2.3
│ │ │ ├── camelcase@2.1.1
│ │ │ ├── ccount@1.0.1
│ │ │ ├─┬ chalk@1.1.3
│ │ │ │ ├── ansi-styles@2.2.1
│ │ │ │ ├── escape-string-regexp@1.0.5
│ │ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ │ └── ansi-regex@2.0.0
│ │ │ │ ├── strip-ansi@3.0.1
│ │ │ │ └── supports-color@2.0.0
│ │ │ ├─┬ chokidar@1.6.0
│ │ │ │ ├─┬ anymatch@1.3.0
│ │ │ │ │ └─┬ micromatch@2.3.11
│ │ │ │ │   ├─┬ arr-diff@2.0.0
│ │ │ │ │   │ └── arr-flatten@1.0.1
│ │ │ │ │   ├── array-unique@0.2.1
│ │ │ │ │   ├─┬ braces@1.8.5
│ │ │ │ │   │ ├─┬ expand-range@1.8.2
│ │ │ │ │   │ │ └─┬ fill-range@2.2.3
│ │ │ │ │   │ │   ├── is-number@2.1.0
│ │ │ │ │   │ │   ├─┬ isobject@2.1.0
│ │ │ │ │   │ │   │ └── isarray@1.0.0
│ │ │ │ │   │ │   └── randomatic@1.1.5
│ │ │ │ │   │ ├── preserve@0.2.0
│ │ │ │ │   │ └── repeat-element@1.1.2
│ │ │ │ │   ├─┬ expand-brackets@0.1.5
│ │ │ │ │   │ └── is-posix-bracket@0.1.1
│ │ │ │ │   ├── extglob@0.3.2
│ │ │ │ │   ├── filename-regex@2.0.0
│ │ │ │ │   ├─┬ kind-of@3.0.4
│ │ │ │ │   │ └── is-buffer@1.1.4
│ │ │ │ │   ├── normalize-path@2.0.1
│ │ │ │ │   ├─┬ object.omit@2.0.0
│ │ │ │ │   │ ├─┬ for-own@0.1.4
│ │ │ │ │   │ │ └── for-in@0.1.6
│ │ │ │ │   │ └── is-extendable@0.1.1
│ │ │ │ │   ├─┬ parse-glob@3.0.4
│ │ │ │ │   │ ├── glob-base@0.3.0
│ │ │ │ │   │ └── is-dotfile@1.0.2
│ │ │ │ │   └─┬ regex-cache@0.4.3
│ │ │ │ │     ├── is-equal-shallow@0.1.3
│ │ │ │ │     └── is-primitive@2.0.0
│ │ │ │ ├── async-each@1.0.1
│ │ │ │ ├── UNMET OPTIONAL DEPENDENCY fsevents@^1.0.0
│ │ │ │ ├── glob-parent@2.0.0
│ │ │ │ ├─┬ is-binary-path@1.0.1
│ │ │ │ │ └── binary-extensions@1.7.0
│ │ │ │ ├─┬ is-glob@2.0.1
│ │ │ │ │ └── is-extglob@1.0.0
│ │ │ │ └─┬ readdirp@2.1.0
│ │ │ │   ├── graceful-fs@4.1.9
│ │ │ │   ├─┬ readable-stream@2.1.5
│ │ │ │   │ ├── buffer-shims@1.0.0
│ │ │ │   │ └── isarray@1.0.0
│ │ │ │   └── set-immediate-shim@1.0.1
│ │ │ ├── collapse-white-space@1.0.2
│ │ │ ├─┬ commander@2.9.0
│ │ │ │ └── graceful-readlink@1.0.1
│ │ │ ├─┬ concat-stream@1.5.2
│ │ │ │ ├─┬ readable-stream@2.0.6
│ │ │ │ │ ├── core-util-is@1.0.2
│ │ │ │ │ ├── isarray@1.0.0
│ │ │ │ │ ├── process-nextick-args@1.0.7
│ │ │ │ │ ├── string_decoder@0.10.31
│ │ │ │ │ └── util-deprecate@1.0.2
│ │ │ │ └── typedarray@0.0.6
│ │ │ ├─┬ debug@2.2.0
│ │ │ │ └── ms@0.7.1
│ │ │ ├── elegant-spinner@1.0.1
│ │ │ ├── extend.js@0.0.2
│ │ │ ├── glob@6.0.4
│ │ │ ├─┬ globby@4.1.0
│ │ │ │ ├─┬ array-union@1.0.2
│ │ │ │ │ └── array-uniq@1.0.3
│ │ │ │ ├── arrify@1.0.1
│ │ │ │ ├── pify@2.3.0
│ │ │ │ └─┬ pinkie-promise@2.0.1
│ │ │ │   └── pinkie@2.0.4
│ │ │ ├── he@0.5.0
│ │ │ ├─┬ log-update@1.0.2
│ │ │ │ ├── ansi-escapes@1.4.0
│ │ │ │ └─┬ cli-cursor@1.0.2
│ │ │ │   └─┬ restore-cursor@1.0.1
│ │ │ │     ├── exit-hook@1.1.1
│ │ │ │     └── onetime@1.1.0
│ │ │ ├── longest-streak@1.0.0
│ │ │ ├── markdown-table@0.4.0
│ │ │ ├─┬ minimatch@3.0.3
│ │ │ │ └─┬ brace-expansion@1.1.6
│ │ │ │   ├── balanced-match@0.4.2
│ │ │ │   └── concat-map@0.0.1
│ │ │ ├─┬ npm-prefix@1.2.0
│ │ │ │ ├── shellsubstitute@1.1.0
│ │ │ │ └── untildify@2.1.0
│ │ │ ├─┬ parse-entities@1.1.0
│ │ │ │ ├── character-entities@1.1.0
│ │ │ │ ├── character-entities-legacy@1.0.1
│ │ │ │ ├── character-reference-invalid@1.0.1
│ │ │ │ ├─┬ has@1.0.1
│ │ │ │ │ └── function-bind@1.1.0
│ │ │ │ ├─┬ is-alphanumerical@1.0.0
│ │ │ │ │ └── is-alphabetical@1.0.0
│ │ │ │ ├── is-decimal@1.0.0
│ │ │ │ └── is-hexadecimal@1.0.0
│ │ │ ├── repeat-string@1.5.4
│ │ │ ├─┬ stringify-entities@1.2.0
│ │ │ │ └── character-entities-html4@1.0.1
│ │ │ ├── to-vfile@1.0.0
│ │ │ ├── trim@0.0.1
│ │ │ ├── trim-trailing-lines@1.0.0
│ │ │ ├─┬ unified@2.1.4
│ │ │ │ ├── attach-ware@1.1.1
│ │ │ │ ├── bail@1.0.1
│ │ │ │ ├── extend@3.0.0
│ │ │ │ └── unherit@1.1.0
│ │ │ ├── user-home@2.0.0
│ │ │ ├── vfile@1.4.0
│ │ │ ├── vfile-find-down@1.0.0
│ │ │ ├── vfile-find-up@1.0.0
│ │ │ ├─┬ vfile-reporter@1.5.0
│ │ │ │ ├── log-symbols@1.0.2
│ │ │ │ ├─┬ plur@2.1.2
│ │ │ │ │ └── irregular-plurals@1.2.0
│ │ │ │ ├─┬ string-width@1.0.2
│ │ │ │ │ ├─┬ code-point-at@1.0.1
│ │ │ │ │ │ └── number-is-nan@1.0.1
│ │ │ │ │ └── is-fullwidth-code-point@1.0.0
│ │ │ │ ├── text-table@0.2.0
│ │ │ │ └── vfile-sort@1.0.0
│ │ │ └─┬ ware@1.3.0
│ │ │   └─┬ wrap-fn@0.1.5
│ │ │     └── co@3.1.0
│ │ ├─┬ remark-html@2.0.2
│ │ │ ├── detab@1.0.2
│ │ │ ├── normalize-uri@1.0.0
│ │ │ ├── object-assign@4.1.0
│ │ │ ├── trim-lines@1.0.0
│ │ │ └── unist-util-visit@1.1.0
│ │ └── word-wrap@1.1.0
│ ├── minimist@1.2.0
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├─┬ multiblob@1.10.2
│ │ ├── blake2s@1.0.1
│ │ ├── pull-defer@0.2.2
│ │ ├─┬ pull-glob@1.0.6
│ │ │ └─┬ pull-fs@1.1.6
│ │ │   └── pull-traverse@1.0.3
│ │ ├── pull-live@1.0.1
│ │ ├── pull-notify@0.0.2
│ │ ├── pull-write-file@0.2.1
│ │ ├─┬ rc@0.5.5
│ │ │ ├── deep-extend@0.2.11
│ │ │ ├── ini@1.3.4
│ │ │ ├── minimist@0.0.10
│ │ │ └── strip-json-comments@0.1.3
│ │ └── rimraf@2.2.8
│ ├── multicb@1.2.1
│ ├─┬ muxrpc@6.3.3
│ │ ├── packet-stream@2.0.0
│ │ ├─┬ packet-stream-codec@1.1.1
│ │ │ ├── pull-reader@1.2.8
│ │ │ └─┬ pull-through@1.0.18
│ │ │   └── looper@3.0.0
│ │ └── pull-goodbye@0.0.1
│ ├─┬ muxrpc-validation@2.0.1
│ │ └─┬ pull-stream@2.28.4
│ │   └── pull-core@1.1.0
│ ├─┬ muxrpcli@1.0.5
│ │ └─┬ pull-stream@2.28.4
│ │   └── pull-core@1.1.0
│ ├── nan@2.4.0 extraneous
│ ├── non-private-ip@1.1.0
│ ├─┬ observ-debounce@1.1.1
│ │ └── observ@0.2.0
│ ├── on-change-network@0.0.2
│ ├── on-wakeup@1.0.1
│ ├── pull-abortable@4.0.0
│ ├── pull-cat@1.1.11
│ ├─┬ pull-file@0.5.0
│ │ └── pull-utf8-decoder@1.0.2
│ ├─┬ pull-inactivity@2.1.1
│ │ └─┬ pull-stream@2.26.1
│ │   └── pull-core@1.1.0
│ ├─┬ pull-level@2.0.3
│ │ ├─┬ level-post@1.0.5
│ │ │ └── ltgt@2.1.2
│ │ └─┬ pull-window@2.1.4
│ │   └── looper@2.0.0
│ ├─┬ pull-many@1.0.6
│ │ └─┬ pull-stream@2.27.0
│ │   └── pull-core@1.1.0
│ ├─┬ pull-notify@0.0.0
│ │ └─┬ pull-pushable@1.1.4
│ │   └── pull-stream@2.18.3
│ ├── pull-paramap@1.1.6
│ ├── pull-ping@1.0.1
│ ├── pull-pushable@2.0.1
│ ├── pull-stream@3.4.5
│ ├── pull-stream-to-stream@1.3.3
│ ├── pull-stringify@1.2.2
│ ├─┬ rimraf@2.5.4
│ │ └─┬ glob@7.1.0
│ │   ├── fs.realpath@1.0.0
│ │   ├─┬ inflight@1.0.5
│ │   │ └── wrappy@1.0.2
│ │   ├── inherits@2.0.3
│ │   ├── once@1.4.0
│ │   └── path-is-absolute@1.0.1
│ ├─┬ secret-stack@3.0.1
│ │ ├── hoox@0.0.1
│ │ ├── map-merge@1.1.0
│ │ ├─┬ multiserver@1.6.0
│ │ │ ├─┬ pull-ws@3.2.6
│ │ │ │ ├── relative-url@1.0.2
│ │ │ │ └─┬ ws@1.1.1
│ │ │ │   ├── options@0.0.6
│ │ │ │   └── ultron@1.0.2
│ │ │ ├─┬ secret-handshake@1.1.1
│ │ │ │ ├── deep-equal@1.0.1
│ │ │ │ ├─┬ pull-box-stream@1.0.11
│ │ │ │ │ ├── increment-buffer@1.0.0
│ │ │ │ │ └── split-buffer@1.0.0
│ │ │ │ └─┬ pull-handshake@1.1.4
│ │ │ │   └── pull-pair@1.1.0
│ │ │ ├── separator-escape@0.0.0
│ │ │ └─┬ socks@1.1.9
│ │ │   ├── ip@1.1.3
│ │ │   └── smart-buffer@1.0.11
│ │ └── non-private-ip@1.3.0
│ ├─┬ secure-scuttlebutt@15.4.2
│ │ ├── deep-equal@0.2.2
│ │ ├─┬ level@1.4.0
│ │ │ ├─┬ level-packager@1.2.0
│ │ │ │ └─┬ levelup@1.3.2
│ │ │ │   ├─┬ deferred-leveldown@1.2.1
│ │ │ │   │ └── abstract-leveldown@2.4.1
│ │ │ │   ├── level-codec@6.1.0
│ │ │ │   ├── level-errors@1.0.4
│ │ │ │   ├── level-iterator-stream@1.3.1
│ │ │ │   └── prr@1.0.1
│ │ │ └─┬ leveldown@1.4.6
│ │ │   ├── abstract-leveldown@2.4.1
│ │ │   ├── bindings@1.2.1
│ │ │   ├── fast-future@1.0.1
│ │ │   ├── nan@2.3.5
│ │ │   └─┬ prebuild@4.2.2
│ │ │     ├── async@1.5.2
│ │ │     ├── expand-template@1.0.3
│ │ │     ├─┬ ghreleases@1.0.5
│ │ │     │ ├── after@0.8.2
│ │ │     │ ├── ghrepos@2.0.0
│ │ │     │ ├─┬ ghutils@3.2.0
│ │ │     │ │ └─┬ jsonist@1.2.0
│ │ │     │ │   ├─┬ bl@1.0.3
│ │ │     │ │   │ └─┬ readable-stream@2.0.6
│ │ │     │ │   │   └── isarray@1.0.0
│ │ │     │ │   └─┬ hyperquest@1.2.0
│ │ │     │ │     ├─┬ duplexer2@0.0.2
│ │ │     │ │     │ └── readable-stream@1.1.14
│ │ │     │ │     └── through2@0.6.5
│ │ │     │ ├── simple-mime@0.1.0
│ │ │     │ └── url-template@2.0.8
│ │ │     ├── github-from-package@0.0.0
│ │ │     ├─┬ node-gyp@3.4.0
│ │ │     │ ├── fstream@1.0.10
│ │ │     │ ├── glob@7.1.0
│ │ │     │ ├─┬ nopt@3.0.6
│ │ │     │ │ └── abbrev@1.0.9
│ │ │     │ ├─┬ osenv@0.1.3
│ │ │     │ │ └── os-tmpdir@1.0.2
│ │ │     │ ├─┬ path-array@1.0.1
│ │ │     │ │ └─┬ array-index@1.0.0
│ │ │     │ │   └─┬ es6-symbol@3.1.0
│ │ │     │ │     ├── d@0.1.1
│ │ │     │ │     └─┬ es5-ext@0.10.12
│ │ │     │ │       └── es6-iterator@2.0.0
│ │ │     │ ├─┬ request@2.75.0
│ │ │     │ │ ├── aws-sign2@0.6.0
│ │ │     │ │ ├── aws4@1.4.1
│ │ │     │ │ ├─┬ bl@1.1.2
│ │ │     │ │ │ └─┬ readable-stream@2.0.6
│ │ │     │ │ │   └── isarray@1.0.0
│ │ │     │ │ ├── caseless@0.11.0
│ │ │     │ │ ├─┬ combined-stream@1.0.5
│ │ │     │ │ │ └── delayed-stream@1.0.0
│ │ │     │ │ ├── forever-agent@0.6.1
│ │ │     │ │ ├─┬ form-data@2.0.0
│ │ │     │ │ │ └── asynckit@0.4.0
│ │ │     │ │ ├─┬ har-validator@2.0.6
│ │ │     │ │ │ └─┬ is-my-json-valid@2.15.0
│ │ │     │ │ │   ├── generate-function@2.0.0
│ │ │     │ │ │   ├─┬ generate-object-property@1.2.0
│ │ │     │ │ │   │ └── is-property@1.0.2
│ │ │     │ │ │   └── jsonpointer@4.0.0
│ │ │     │ │ ├─┬ hawk@3.1.3
│ │ │     │ │ │ ├── boom@2.10.1
│ │ │     │ │ │ ├── cryptiles@2.0.5
│ │ │     │ │ │ ├── hoek@2.16.3
│ │ │     │ │ │ └── sntp@1.0.9
│ │ │     │ │ ├─┬ http-signature@1.1.1
│ │ │     │ │ │ ├── assert-plus@0.2.0
│ │ │     │ │ │ ├─┬ jsprim@1.3.1
│ │ │     │ │ │ │ ├── extsprintf@1.0.2
│ │ │     │ │ │ │ ├── json-schema@0.2.3
│ │ │     │ │ │ │ └── verror@1.3.6
│ │ │     │ │ │ └─┬ sshpk@1.10.1
│ │ │     │ │ │   ├── asn1@0.2.3
│ │ │     │ │ │   ├── assert-plus@1.0.0
│ │ │     │ │ │   ├── bcrypt-pbkdf@1.0.0
│ │ │     │ │ │   ├─┬ dashdash@1.14.0
│ │ │     │ │ │   │ └── assert-plus@1.0.0
│ │ │     │ │ │   ├── ecc-jsbn@0.1.1
│ │ │     │ │ │   ├─┬ getpass@0.1.6
│ │ │     │ │ │   │ └── assert-plus@1.0.0
│ │ │     │ │ │   ├── jodid25519@1.0.2
│ │ │     │ │ │   └── jsbn@0.1.0
│ │ │     │ │ ├── is-typedarray@1.0.0
│ │ │     │ │ ├── isstream@0.1.2
│ │ │     │ │ ├── json-stringify-safe@5.0.1
│ │ │     │ │ ├─┬ mime-types@2.1.12
│ │ │     │ │ │ └── mime-db@1.24.0
│ │ │     │ │ ├── node-uuid@1.4.7
│ │ │     │ │ ├── oauth-sign@0.8.2
│ │ │     │ │ ├── qs@6.2.1
│ │ │     │ │ ├── stringstream@0.0.5
│ │ │     │ │ ├── tough-cookie@2.3.1
│ │ │     │ │ └── tunnel-agent@0.4.3
│ │ │     │ ├─┬ tar@2.2.1
│ │ │     │ │ └── block-stream@0.0.9
│ │ │     │ └─┬ which@1.2.11
│ │ │     │   └── isexe@1.1.2
│ │ │     ├── node-ninja@1.0.2
│ │ │     ├── noop-logger@0.1.1
│ │ │     ├─┬ npmlog@2.0.4
│ │ │     │ ├── ansi@0.3.1
│ │ │     │ ├─┬ are-we-there-yet@1.1.2
│ │ │     │ │ ├── delegates@1.0.0
│ │ │     │ │ └─┬ readable-stream@2.1.5
│ │ │     │ │   └── isarray@1.0.0
│ │ │     │ └─┬ gauge@1.2.7
│ │ │     │   ├── has-unicode@2.0.1
│ │ │     │   ├── lodash.pad@4.5.1
│ │ │     │   ├── lodash.padend@4.6.1
│ │ │     │   └── lodash.padstart@4.6.1
│ │ │     ├─┬ pump@1.0.1
│ │ │     │ └─┬ end-of-stream@1.1.0
│ │ │     │   └── once@1.3.3
│ │ │     ├─┬ simple-get@1.4.3
│ │ │     │ └── unzip-response@1.0.1
│ │ │     ├── tar-fs@1.13.2
│ │ │     └─┬ tar-stream@1.5.2
│ │ │       ├─┬ bl@1.1.2
│ │ │       │ └── readable-stream@2.0.6
│ │ │       └─┬ readable-stream@2.1.5
│ │ │         └── isarray@1.0.0
│ │ ├─┬ level-peek@2.0.1
│ │ │ └── pull-stream@2.24.1
│ │ ├─┬ level-sublevel@6.6.0
│ │ │ ├─┬ bytewise@1.1.0
│ │ │ │ ├─┬ bytewise-core@1.2.3
│ │ │ │ │ └── typewise-core@1.2.0
│ │ │ │ └── typewise@1.0.3
│ │ │ ├─┬ levelup@0.19.1
│ │ │ │ ├── bl@0.8.2
│ │ │ │ ├─┬ deferred-leveldown@0.2.0
│ │ │ │ │ └─┬ abstract-leveldown@0.12.4
│ │ │ │ │   └── xtend@3.0.0
│ │ │ │ ├── errno@0.1.4
│ │ │ │ ├── prr@0.0.0
│ │ │ │ ├─┬ readable-stream@1.0.34
│ │ │ │ │ └── isarray@0.0.1
│ │ │ │ ├── semver@5.1.1
│ │ │ │ └── xtend@3.0.0
│ │ │ ├── ltgt@2.1.2
│ │ │ ├── pull-stream@2.21.0
│ │ │ └── xtend@4.0.1
│ │ ├── ltgt@2.0.0
│ │ ├── monotonic-timestamp@0.0.9
│ │ ├── pull-notify@0.1.1
│ │ ├── pull-write@1.1.0
│ │ ├─┬ ssb-keys@6.1.2
│ │ │ └── private-box@0.2.1
│ │ └── typewiselite@1.0.0
│ ├─┬ ssb-blobs@0.1.6
│ │ ├── pull-level@1.5.2
│ │ └── pull-notify@0.1.1
│ ├─┬ ssb-client@4.2.1
│ │ └─┬ ssb-keys@6.1.2
│ │   └── deep-equal@0.2.2
│ ├─┬ ssb-config@2.1.1
│ │ ├── deep-extend@0.4.1
│ │ ├── non-private-ip@1.3.0
│ │ ├── os-homedir@1.0.2
│ │ └─┬ rc@1.1.6
│ │   └── strip-json-comments@1.0.4
│ ├─┬ ssb-feed@2.2.1
│ │ └─┬ ssb-keys@6.1.2
│ │   └── deep-equal@0.2.2
│ ├─┬ ssb-keys@5.1.2
│ │ ├─┬ chloride@2.2.3
│ │ │ ├── is-electron@2.0.0
│ │ │ ├─┬ sodium-browserify@1.2.0
│ │ │ │ ├─┬ libsodium-wrappers@0.2.12
│ │ │ │ │ └── libsodium@0.2.12
│ │ │ │ ├── sha.js@2.4.5
│ │ │ │ └── tweetnacl@0.14.3
│ │ │ ├─┬ sodium-browserify-tweetnacl@0.2.1
│ │ │ │ ├─┬ chloride-test@1.1.1
│ │ │ │ │ └── json-buffer@2.0.11
│ │ │ │ ├── ed2curve@0.1.4
│ │ │ │ └── tweetnacl-auth@0.3.0
│ │ │ └── UNMET OPTIONAL DEPENDENCY sodium-prebuilt@^1.0.22
│ │ ├── deep-equal@0.2.2
│ │ ├── hmac@1.0.1
│ │ └── private-box@0.0.3
│ ├── ssb-msgs@5.0.0
│ ├─┬ ssb-ref@2.6.0
│ │ ├── ip@1.1.3
│ │ └── is-valid-domain@0.0.2
│ ├── statistics@2.0.1
│ ├─┬ stream-to-pull-stream@1.7.2
│ │ └── looper@3.0.0
│ └── zerr@1.0.4

**Comment by dominictarr** [comment]
okay, I got through to your server using ssb-client...

**Comment by dominictarr** [comment]
okay, I figured out what it is. it's that the client multiserver definition doesn't actually get used
https://github.com/ssbc/secret-stack/blob/master/index.js#L87-L91

instead, the connection gets created from here:
https://github.com/ssbc/secret-stack/blob/master/index.js#L135-L137

am thinking that multiserver should just take an option to disable the server modes?

**Comment by arj03** [comment]
Yeah exactly that's what I got as well.

**Comment by dominictarr** [comment]
Ah, dang, I didn't see that one right.
I think we just need a way to tell multiserver not to create a server for some protocols...

maybe `{server: false}`, that is supported by `ws` already.
https://github.com/dominictarr/multiserver/blob/58d53b72bf2d7fcb3f7ebfa19b2f22d5bae76268/plugins/ws.js#L16

**Comment by arj03** [comment]
Makes sense. I'll do a PR for that. 

While we are at it, what are protocols used for in multiserver? Because as it is now, onion.js still uses tproxy so that makes me think its not used at all?

**Comment by dominictarr** [comment]
do you mean the protocol field? hmm, nothing actually, since it just passes it to every parser, and uses the first one.

if you mean on the string, `net:...` for example, then the handler for net checks that, and returns an address string that it can recognise (via `stringify()`) so it's easy to add more protocols because it can distinguish them easily.

**Comment by arj03** [comment]
Sorry, I mean this file :)

https://github.com/dominictarr/multiserver/blob/master/protocols/onion.js

**Comment by dominictarr** [comment]
oh, I didn't realize that was still there. it's a duplicate. should delete `./protocols`, that, and `./transforms` too.

**Comment by arj03** [comment]
Okay, I'll do that in my PR also then 👍

**Comment by arj03** [comment]
Cool. Now I got gossip connect working as well!

**Comment by dominictarr** [comment]
merged this into ssb-patchwork@2.11.0
@mmckegg @clehner can we do new releases?

@fredhampton if you use this version you should be right

**Comment by fredhampton** [comment]
Thanks so much !!!!!


On October 7, 2016 at 4:12:37 PM, Dominic Tarr (notifications@github.com) wrote:

merged this into ssb-patchwork@2.11.0
@mmckegg @clehner can we do new releases?

@fredhampton if you use this version you should be right

**Comment by mmckegg** [comment]
@dominictarr about to do a mac release now, but the linux one will have to wait til tomorrow!

**Pull request merged**
