### PR TITLE
Add font settings

### PR DESCRIPTION
**Pull request by christianbundy**
I've taken the [most common values for `font-family`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family) and added them to the settings page. This makes it easy to switch font types, intuitive to hack in custom values, and serves as a good foothold for future work on font customization.

screenshot from 2018-08-15 18-24-46

screenshot from 2018-08-15 18-24-55

screenshot from 2018-08-15 18-25-08

The only regression I've found is that the "Attach File" button has a fixed width that's cut off when I use monospace, but I'm not sure whether/how that should be resolved:

screenshot from 2018-08-15 18-25-46

### CODE REVIEW

**Comment by mmckegg** [comment]
@christianbundy Hmm, I'll give this some thought. First reaction is that I'd prefer it just being easier to make custom themes than adding more font settings to the screen.

I'm really keen to figure out a way to unify the light and dark themes (the shared styles).  Want to start experimenting with css variables like what @mixmix has been doing in patchbay.

**Comment by christianbundy** [comment]
No problem, I think custom themes would be much more expressive. Let's go that route instead! I sent some you some context on this PR as `%hNZOQk8Z3M6GnpcuLJ0mRXPI6VbWLjW+kfNtMVRhABs=.sha256`. I love the variable-based setup that Patchbay has started with, so I'd be happy to help with that sort of thing in Patchwork as well.

**Comment by mixmix** [comment]
Hey Christian heads up that patchwork has a couple of outstanding PRs which
have been open a while and matt has very little capacity (and is the main
sole maintainer of pw).
I think what I'm asking is that your attention and care is good but please
know there's this context and to keep an eye on how many open PRs there are
ahead of things you open.
That feels stink to say, but i really want those PRs to get in

**Comment by christianbundy** [comment]
@mixmix 

That makes sense, I appreciate you letting me know. For the sake of transparency, I opened this as a PR for visibility [here](%9u6lCYklBgZl7iDM58kVzVW0/sZ1IC7f4eRh0jr4J0o=.sha256), and sent this to @mmckegg:

> Hey! Just wanted to give you some context on [this PR](https://github.com/ssbc/patchwork/pull/846) -- I wrote it in response to [this thread](%9u6lCYklBgZl7iDM58kVzVW0/sZ1IC7f4eRh0jr4J0o=.sha256) to serve as a foothold for [contributions], so I won't have any hurt feelings if you don't merge the branch as-is (or at all!).

I'm sorry, I didn't consider that this would detract from other code. Is there anything I can do to help with more important work? Maybe after those PRs are merged I can help with easy theming and CSS variables like Matt mentioned above, but I'll leave the Patchwork codebase alone for a while unless I notice something really critical. :+1:

**Comment by mixmix** [comment]
Actually the theming fixes would help this get merged,it's an ongoing thing
and if you wanted to take a stab at it would be a massive help.

Basically the idea is to :
-make light theme default
- apply light css first, then optionally dark css, instead of one or other
(this would make css a merge and dark would be override)
- refractor dark and light to use css variables more

What's needed is then a careful diffing of the themes, and in some cases a
manual merge (apparently dark theme has better layout and logic some of
which would be good to port).

Happy to get on a call and discuss or talk through if you're interested to
help

**Comment by mixmix** [comment]
If you are pm me on ssb. I have signal /telegram / wire and am in nz
timezone

**Comment by christianbundy** [comment]
I had a friend request serif fonts in Patchwork and was bummed to tell them there was no way to change the font. I started looking at the code to see if this would be possible to hack in, and then remembered :bulb: hey I already wrote this feature!

The theme diffing work mentioned above was resolved in #850, so I think this branch should be good to go now:

Screenshot from 2019-06-09 13-04-19

Screenshot from 2019-06-09 13-05-07

**Comment by black-puppydog** [comment]
For me, `serif`, `cursive` and `fantasy` all seem to look identical. Might be that I'm lacking the right font packages? This is on KDE neon, so based on Ubuntu 18.04 LTS

**Comment by black-puppydog** [comment]
I should mention that browsing ssb in monospace looks awesome! :)

**Comment by christianbundy** [comment]
Yeah, those only kick in if you have the right fonts. If you don't have the correct font that you've selected then it just falls back to the default (since we can't do font detection very easily). Happy you're digging it in monospace! Let me know if there are any changes you'd like to see on this branch.

**Comment by black-puppydog** [comment]
Been scuttlin' for a few hours with this now and I like it :)

**Comment by christianbundy** [comment]
@black-puppydog 

Thanks for the time spent reviewing! Happy to hear it worked alright.

**Pull request merged**
