### PR TITLE
Feed / Nav Updates

### PR DESCRIPTION
**Pull request by pfraze**
[Video demonstrating this PR's changes](https://www.youtube.com/watch?v=neHjJHyiA1g&feature=youtu.be) (I figured a video would be easier than writing it all up)

Supercedes https://github.com/ssbc/patchwork/pull/282

### CODE REVIEW

**Comment by pfraze** [comment]
Sorry this one's so big. It got away from me a bit.

**Comment by clehner** [comment]
:+1:

I like the left sidebar changes and making "All talk" primary. I like the new composer preview too. However with longer messages it overflows into the feed.

The indication of unread using grey slashes I find sometimes too subtle to notice (especially if I am looking at my LCD screen from a high angle). The bold text stands out much more, but that is the message's own formatting.

**Comment by jrf0110** [comment]
Feel like the main inbox view should grow with the container a bit more. It feels cramped:

image

**Comment by jrf0110** [comment]
Composition box should stretch the main container width and avatar should be in the gutter

image

**Comment by pfraze** [comment]
@clehner I agree, so I tweaked it a bit. Bold only appears in unread items now:

screen shot 2016-02-06 at 3 52 50 pm

@jrf0110 yeah I plan to play with the widths later

**Comment by pfraze** [comment]
Went ahead and added tooltips using https://github.com/chinchang/hint.css

tooltips

**Comment by pfraze** [comment]
Trying to decide if I like having images in the posts, not sure if I do.

**Comment by pfraze** [comment]
Thanks for the feedback all! Going to go ahead and merge, will publish as a new patchwork version (minor bump) tomorrow.

**Pull request merged**
