### PR TITLE
support rotation of avatars while cropping

### PR DESCRIPTION
**Pull request by dominictarr**
My new avatar was showing sideways so I added rotation to the cropping tool.

(I don't know why, because it does render up the right way when you open it in any other photo app, but anyway, now we can rotate avatars)

### CODE REVIEW

**Comment by pfraze** [comment]
ok cool, let me poke at it and see if I cant get rid of that settimeout magic

**Comment by dominictarr** [comment]
awesome!

**Comment by dominictarr** [comment]
did you figure this out? can we merge?

**Comment by pfraze** [comment]
I'll try to get this tonight

**Comment by pfraze** [comment]
@dominictarr setState() is an async operation, you just needed to use a callback

**Comment by dominictarr** [comment]
oh i didn't realize it was async because the other uses didn't use it with a callback.
Why is it async? does it update the state in the next frame?

**Comment by pfraze** [comment]
From docs:

> setState() does not immediately mutate this.state but creates a pending state transition. Accessing this.state after calling this method can potentially return the existing value.

You only need to pass a CB if the following code depends on the updated `this.state`

**Comment by dominictarr** [comment]
@pfraze another question: is there a way to have something trigger after the state changes? does it need to be in the render function for that? If you have something like a canvas in there (as in this code) it breaks the functional thing to explicitly call drawCanvas, after each update, really react should just call that somehow.

**Pull request merged**
