### PR TITLE
Use "device" scope for unix socket

### LINKED ISSUE #943: possible malformed 'remote' prevents discovery of patchwork ssb instance on LAN?
I'm having trouble discovering and following patchwork ssb client running on my laptop from Manyverse on my phone and it appears information may be missing from patchwork's broadcast discovery packets. 

I previously opened a ticket for Manyverse https://gitlab.com/staltz/manyverse/issues/333 and followed suggestion from staltz to capture the UDP packets sent to 255.255.255.255 using wireshark

The packets from laptop (patchwork) look like:
```
ÿÿÿÿÿÿtå¹EBúÔ@@}ÄÀ¨jÿÿÿÿHH.á:unix:/home/skyebend/.ssb/socket~noauth
```
vs. packets from phone (manyverse) look like:
```
ÿÿÿÿÿÿ´ÎöýEd@@xpÀ¨qÿÿÿÿHHP.énet:192.168.1.113:26831~shs:MhGNu6tzZHSNv4U6nLRMVdnbvv+YLudFm5nqKqo7QJQ=
```
This makes it look like patchwork is  broadcasting a unix path instead of an IP and port for discovery? and maybe also omitting the identity?

This seems to align with the config data printed by patchwork at startup
```
remote: 'unix:/home/skyebend/.ssb/socket:~noauth:F/Lw6U9khCl8f/BrfYbSnsd1jMFqK+9otnyKBwfp9Es=' }
```
Am I missing some configuration somewhere?  Something needs to be set to 'net' instead of 'unix'? Is there a reference on what is supposed to be in the broadcast packets?

I'm using patchwork built from source from this repo (at git commit 9750bc4d761e9243e144df7ecbc35c38e2b0a04e) on Ubuntu (32bit so couldn't install directly)

### PR DESCRIPTION
**Pull request by christianbundy**
Resolves #943 

cc: @skyebend, could you verify that this resolves the issue for you locally?

### CODE REVIEW

**Comment by skyebend** [comment]
when I tried to run on this branch I get
```
> ssb-patchwork@3.12.0-dev start /home/skyebend/ssb
> electron index.js

error loading sodium bindings: /home/skyebend/ssb/node_modules/sodium-native/build/Release/sodium.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi
falling back to javascript version.
{ path: '/home/skyebend/.ssb',
  party: true,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  gossip: { connections: 3, autoPopulate: false },
  host: '',
  port: 8008,
  ws: { port: 8989 },
  connections: 
   { outgoing: { net: [Array] },
     incoming: { net: [Array], ws: [Array], unix: [Array] } },
  timers: { connection: 0, reconnect: 5000, ping: 300000, handshake: 5000 },
  caps: 
   { shs: '1KHLiKZvAvjbY1ziZEHMXawbCEIM6qwjCDm3VYRan/s=',
     sign: null },
  master: [],
  logging: { level: 'notice' },
  blobsPort: 8989,
  server: true,
  _: [],
  keys: 
   { curve: 'ed25519',
     public: 'F/Lw6U9khCl8f/BrfYbSnsd1jMFqK+9otnyKBwfp9Es=.ed25519',
     private: null,
     id: '@F/Lw6U9khCl8f/BrfYbSnsd1jMFqK+9otnyKBwfp9Es=.ed25519' },
  remote: 'unix:/home/skyebend/.ssb/socket:~noauth:F/Lw6U9khCl8f/BrfYbSnsd1jMFqK+9otnyKBwfp9Es=' }
error loading sodium bindings: /home/skyebend/ssb/node_modules/sodium-native/build/Release/sodium.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi
falling back to javascript version.
Init replication limiter. maxNumConnections: 10, modeChangeThreshold: 100
Replication obs called, Limited mode enabled:  false
git-ssb is not installed, or not available in path
Listening on undefined:8008 (multiserver net plugin)
listening on socket unix:/home/skyebend/.ssb/socket
error loading sodium bindings: /home/skyebend/ssb/node_modules/sodium-native/build/Release/sodium.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi
falling back to javascript version.
unix socket client
Error {}
Error {}
Error {}
Error {}
Error {}
Error {}
Error {}
Error {}
Error {}
Error {}
Error {}
Error {}
Error {}
```
and I see no UDP packets in wireshark

**Comment by christianbundy** [comment]
Hmm, could you `git reset --hard origin/devie-unix-socket && npm ci`? I can't imagine why that would throw an error, the device scope shouldn't break anything.

**Comment by skyebend** [comment]
thanks, after clean reinstall, it runs without error, but I still do not see broadcast packets at all. Maybe that was the intention of this PR?  In other words it is definitely successful preventing it from broadcasting the internal unix path, but it isn't broadcasting the correct ip, port and identity either -- unless I need to do something other than default settings to make this work?

I see complaints about problems with sodium bindings, does this mean I'm missing libraries?  I apologise that I'm not familiar with the tool chain, my first experience with node.

```
> ssb-patchwork@3.12.0-dev start /home/skyebend/ssb
> electron index.js

error loading sodium bindings: /home/skyebend/ssb/node_modules/sodium-native/build/Release/sodium.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi
falling back to javascript version.
{ path: '/home/skyebend/.ssb',
  party: true,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  gossip: { connections: 3, autoPopulate: false },
  host: '',
  port: 8008,
  ws: { port: 8989 },
  connections: 
   { outgoing: { net: [Array] },
     incoming: { net: [Array], ws: [Array], unix: [Array] } },
  timers: { connection: 0, reconnect: 5000, ping: 300000, handshake: 5000 },
  caps: 
   { shs: '1KHLiKZvAvjbY1ziZEHMXawbCEIM6qwjCDm3VYRan/s=',
     sign: null },
  master: [],
  logging: { level: 'notice' },
  blobsPort: 8989,
  server: true,
  _: [],
  keys: 
   { curve: 'ed25519',
     public: 'F/Lw6U9khCl8f/BrfYbSnsd1jMFqK+9otnyKBwfp9Es=.ed25519',
     private: null,
     id: '@F/Lw6U9khCl8f/BrfYbSnsd1jMFqK+9otnyKBwfp9Es=.ed25519' },
  remote: 'unix:/home/skyebend/.ssb/socket:~noauth:F/Lw6U9khCl8f/BrfYbSnsd1jMFqK+9otnyKBwfp9Es=' }
error loading sodium bindings: /home/skyebend/ssb/node_modules/sodium-native/build/Release/sodium.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi
falling back to javascript version.
Init replication limiter. maxNumConnections: 10, modeChangeThreshold: 100
Replication obs called, Limited mode enabled:  false
git-ssb is not installed, or not available in path
Listening on undefined:8008 (multiserver net plugin)
listening on socket unix:/home/skyebend/.ssb/socket
error loading sodium bindings: /home/skyebend/ssb/node_modules/sodium-native/build/Release/sodium.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi
falling back to javascript version.
unix socket client
```

**Comment by christianbundy** [comment]
I'm not sure, this *only* resolves the issue with unix scopes being broadcast but doesn't touch anything else. If you aren't seeing any UDP packets could you open an issue with the relevant info? I'm not quite sure how I'd debug that, but I don't think that it should be coming from this PR.

**Comment by skyebend** [comment]
are you saying that when you run with this branch you **do** see correct UDP packets broadcast? (i.e. I probably have something wrong locally and I'll try to dig in more detail)

**Comment by christianbundy** [comment]
Nope, you're absolutely right -- I've just pushed a commit that upgrades ssb-config to resolve the issue. Now I'm seeing both my net and websocket addresses being broadcast correctly:

```
net:192.168.3.55:8008~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=;ws://192.168.3.55:8989~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
```

**Pull request merged**
