### PR TITLE
Use experimental ssb-config

### LINKED ISSUE #958: Local gossip not working
I just upgraded to 3.11.5 and I cannot gossip with another machine on the same network. The other machine shows up in the "Local" section of the sidebar but messages are not transmitted between the two machines. Messages are transmitted fine when both machines  are running Patchwork 3.11.4.

Machines are running macOS 10.13.6 and 10.14.3
`~/.ssb.config` contents:
```
{
  “caps”: {
     “shs”: “secretkey”
  }
}
```

The `gossip.json` on one machine looked like this:
```
[{"host":"-redacted-","port":8008,"key":"@wnUdsQetC9YeEuW4DW6cC5/Zs8vSwla/u50b4nbshJs=.ed25519","address":"net:fe80::437:72a2:1a8c:9dc5:8008~shs:wnUdsQetC9YeEuW4DW6cC5/Zs8vSwla/u50b4nbshJs=;ws://[::]:8989~shs:-redacted-","source":"local","announcers":1,"duration":{"mean":0,"stdev":0,"count":44,"sum":0,"sqsum":0},"stateChange":1552917690911,"error":"Error: connect EHOSTUNREACH -redacted- - Local (:::50420)\n    at Object._errnoException (util.js:1024:11)\n    at _exceptionWithHostPort (util.js:1046:20)\n    at internalConnect (net.js:971:16)\n    at net.js:1065:9\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","failure":44}]
```

### LINKED ISSUE #1024: Problem loading images (ssb-ws binding to wrong IP)
Version: 3.12.0-beta.0 (3.12.0-beta.0.268) on Mac 10.12.6

Images that don't seem to be cached aren't loading or trying to be fetched.

screen_capture

### PR DESCRIPTION
**Pull request by christianbundy**
Waiting for a code review on https://github.com/ssbc/ssb-config/pull/53 but I want to get a test branch going so that we can ensure that it resolves #958 and resolves #1024.

### CODE REVIEW

**Comment by the-kenny** [comment]
I just tried this branch locally and noticed two strange things:

- It broadcasts multiple identities separated by `;`. Is this documented anywhere? (I like the idea - I just haven't seen it before)
- It broadcasts websocket addresses like `ws://[fe80::aede:48ff:fe00:1122]:8980` (this might be intentional?
- It leaves off the `.ed25519` suffix from the identity. Is this intentional?

**Comment by christianbundy** [comment]
@the-kenny 

Hey! Yeah, this protocol is called [multiserver](https://github.com/ssbc/multiserver), the idea is that you broadcast all of the addresses you're listening on over UDP so that other peers on the network can choose which to connect to. They're *almost* URIs but they have a few small differences.

The websocket server this is intentional, the idea is to support browser clients and such in the future which may not be able to to TCP (but are somehow able to get the multiserver address to connect to).

I think that removing `ed25519` is intentional -- my understanding is that the `~shs` bit of the multiserver address means "I use [secret-handshake](https://github.com/auditdrivencrypto/secret-handshake) for authentication" which [assumes an ed25519 keypair](https://github.com/auditdrivencrypto/secret-handshake/blob/1a6a2a9bda529a7a822c04ede4f1b644b6a12a26/test/net.js#L34).

**Comment by the-kenny** [comment]
> Hey! Yeah, this protocol is called multiserver, the idea is that you broadcast all of the addresses you're listening on over UDP so that other peers on the network can choose which to connect to. They're almost URIs but they have a few small differences.
> The websocket server this is intentional, the idea is to support browser clients and such in the future which may not be able to to TCP (but are somehow able to get the multiserver address to connect to).

Cool! I didn't know that :-) 

> I think that removing `ed25519` is intentional -- my understanding is that the `~shs` bit of the multiserver address means "I use [secret-handshake](https://github.com/auditdrivencrypto/secret-handshake) for authentication" which [assumes an ed25519 keypair](https://github.com/auditdrivencrypto/secret-handshake/blob/1a6a2a9bda529a7a822c04ede4f1b644b6a12a26/test/net.js#L34).

You're totally right. For some reason I thought it required to add the `ed25519` suffix. My bad :-)

**Comment by qubist** [comment]
I think I'm still experiencing #1024.

Can someone check I'm doing the test correctly? I pulled so I'm up to date, switched to the `auto-config` branch, and used `npm start`. I see 49512ab2 when running `git log`, so I know that I have these changes.

When Patchwork opens I still can't see images. clicking on them reveals links like `http://localhost:8989/blobs/get/&/s3EE57hq0dLePHZFV6/WuguCeiAWeftLTZbB4FNQ7Q=.sha256`. If I paste my host ip in place of localhost, the image loads (same as before).

Here's the config JSON: https://pastebin.com/R3Nb6pMC

**Comment by christianbundy** [comment]
@qubist Thanks for helping debug! Did you run `npm install` before running `npm start`?

**Comment by qubist** [comment]
> Did you run npm install before running npm start?

Aha! I did not.

Sure enough, it works now. My Patchwork loads images once again. Happy to help, let me know if I can do more to be helpful :)

**Comment by black-puppydog** [comment]
I had to remove my hardcoded `::` config entry (:man_facepalming:) but now it seems to work. Tested again with `wget -O /tmp/bla.jpg 'http://localhost:8989/blobs/get/&VmqGJubhM08hoQK2JAJEEDC+mKHj1aRFJzsTSc4zFCA=.sha256?contentType=image%2Fjpeg'`. Fails on `master`, works with `auto-config`. Great! :)

**Comment by luandro** [comment]
Solved the image issues I was having with 12 beta, thanks @christianbundy!

**Comment by christianbundy** [comment]
I'm going to merge this so that we can let it bake in `master` and then make a note of it in another issue so that we don't have Git repos in `package.json`. Using a Git repo link is hacky so I'd like this to be removed before the v3.12.0 release but I'm more concerned about having people test these changes.

**Pull request merged**
