### PR TITLE
Add NixOS section to INSTALL.md

### PR DESCRIPTION
**Pull request by fabianhjr**

### CODE REVIEW

**Comment by black-puppydog** [comment]
hmmm... why remove the git dependency? current `master` actually needs it to pull `npm-keys-neon`...

**Comment by fabianhjr** [comment]
Oh shit an oversight, give me a sec to amend.

**Comment by fabianhjr** [comment]
Ok, amended

**Comment by black-puppydog** [comment]
(I rebase-merged this, just to avoid merge commits.)

**Comment by black-puppydog** [comment]
and thanks for all your work! :)

**Pull request merged**
