### PR TITLE
add "Copy External Link" to message context menu

### PR DESCRIPTION
**Pull request by ahdinosaur**
similar to https://github.com/ssbc/patchbay/pull/107

### CODE REVIEW

**Comment by dominictarr** [comment]
👍 ideally we need someone else who can build this (for mac) while matt is taking a break.

**Comment by mmckegg** [comment]
@ahdinosaur  This looks cool! Would be nice to use something similar to gateway for external git links too!

https://github.com/ssbc/patchwork/blob/master/modules/app/sync/external-handler/git.js

**Comment by ahdinosaur** [comment]
agree. maybe related to https://github.com/ssbc/patchwork/pull/448#issuecomment-289344832.

**Comment by mmckegg** [comment]
screen shot 2017-04-23 at 1 43 58 pm

This is looking a little busy! So many "Copy ..."

Wonder if there's a way we can tidy this up a bit?

Maybe it should include the name of the viewer you are using to copy?

**Comment by mmckegg** [comment]
Can we put these inside a sub menu?

**Comment by dominictarr** [comment]
c'mon @mmckegg the context menu is already a junk drawer, lets just merge it.

Or, if you really do want to change it, what about something that used depject to pull in things like https://github.com/dominictarr/patch-context/blob/master/defaults/copy-external.js just to make it much easier to add things?

**Comment by mmckegg** [comment]
Okayyy! 🤣

**Pull request merged**
