### PR TITLE
Backport ssb-server@13 to Patchwork 3.11

### PR DESCRIPTION
**Pull request by christianbundy**
This is a more minimal take on #959, bringing Patchwork up-to-date with ssb-server@13 without trying to make the leap to the bright and shiny ssb-server@14. 

- scuttlebot@12 => ssb-server@13
- ssb-ws@2 => ssb-ws@6
- fixed missing/unused modules in `package.json`:
  - added lodash
  - added run-parallel
  - removed node-abi
- removed `sbot-local-widh-address-fix.js`

---

The goal here is to more closely match `master`, **not** a full upgrade to the latest and greatest.

### CODE REVIEW

**Comment by christianbundy** [comment]
This is also affected by #960, I'm not sure why. :unamused:

**Comment by waynew** [comment]
Does this mean the dht invites (should be able to) work again?

**Comment by christianbundy** [comment]
I'm not sure, I don't remember what the blocker for that was. I thought that they only worked on ssb-server@12 or something but I don't have a clear memory.

**Comment by christianbundy** [comment]
I'm thinking/hoping that we'll get a release from `master` soon. Closing this now because I think it was giving Matt "weird perf issues'.

**Pull request closed without merging**
