### PR TITLE
Optionally filter channel (un)subscribe messages from channel view

### PR DESCRIPTION
**Pull request by mnzaki**
Seems to be a common grievance; added a setting for it.

### CODE REVIEW

**Comment by mmckegg** [comment]
@mnzaki 

Thanks for the pull request! Keen to merge just one thing.

I think this should also have an option for hiding the channel subscription messages from the public feed too. This case is IMO the most important.

Should be two seperate options though since you might still want to see who subscribes to a particular channel.

**Comment by mnzaki** [comment]
I actually started out with one setting (that filters out subscription message from both public and channel) then changed it to channel only, because that's the obnoxious one for me: going to a channel and scrolling through a long list of 'subscribed'/'unsubscribed'. On the other hand, the subscription messages in the public feed are messages from people I'm following; it is actually interesting for me to see.

But anyway, that's a uxer preference! I added a setting for public feed filter as well.

**Comment by hbetts** [comment]
👍 Looks good to me!

**Comment by mmckegg** [comment]
Thanks @mnzaki! Will be in the next release 👍

**Pull request merged**
