### PR TITLE
Replace emoji symlink with real path

### LINKED ISSUE #1053: Emoji broken on windows
@mixmix reported this on 3.12.0 beta 0 and @cblgh reported this on beta 3, both on windows.

### PR DESCRIPTION
**Pull request by christianbundy**
Maybe resolves #1053? This removes the symlink, which is good, but I'm not sure how we can test this.

### CODE REVIEW

**Comment by christianbundy** [comment]
cc @cblgh

**Comment by soapdog** [comment]
Patchwork 2019-05-26 11 47 54

Working fine here.

**Comment by Powersource** [comment]
Thanks! Someone (maybe me in a few hours) should add a changelog entry for this and then I think we can merge.

**Comment by Powersource** [comment]
Although we should probably test this through the windows installer too (guessing you launched from source @soapdog ?)

**Comment by cblgh** [comment]
yeah sorry, couldn't build patchwork for windows (i usually dev on a
headless linux or my mac air)

**Comment by christianbundy** [comment]
Thanks for adding docs! Merging now.

**Pull request merged**
