### PR TITLE
Update content security policy to allow webcam access (media-src blob:)

### PR DESCRIPTION
**Pull request by clehner**
This fixes the webcam problem I was having in #51

Also this adds an error handler to where the error would be caught without the fix (in case it fails for some other reason)

### CODE REVIEW

**Comment by dominictarr** [comment]
@clehner so now this fully works for you?
@pfraze and I where discussing dropping this but if it can be made to work easily, maybe we should keep it?

**Comment by clehner** [comment]
It works fully for me, yes. I can see maybe the feature is a little gimmicky, but I think it's nice

**Comment by dominictarr** [comment]
It would be less gimmicky if it could also be use to take still photos.
I've wanted to do that occasionally.

**Comment by pfraze** [comment]
Thanks for the fix, @clehner. I'll merge this once we know what the plan is with the webcam tools.

**Pull request closed without merging**
