### PR TITLE
Use profile pics in inbox views

### PR DESCRIPTION
**Pull request by pfraze**
Figured this might look nice:

screen shot 2015-11-28 at 12 48 05 pm

Yea/nay?

### CODE REVIEW

**Comment by sedmonds** [comment]
Nice UI alternative, but just that. I'd love to see what happens when adopting the rule of silence in one styleset.

**Comment by pfraze** [comment]
@sedmonds what would the rule of silence in a stylesheet look like?

**Comment by sedmonds** [comment]
A lot. Will attempt to distill my thoughts on Patch.

**Comment by mixmix** [comment]
I'd love to start a list of things to allow users to customise. This seems like a nice thing to offer as toggleable
Personally I love the images, adds color and fast to read. Might be phishing-vulnerable.

**Comment by dominictarr** [comment]
I would approve of this - but @mixmix does have a point about phishing - it should be possible to set someone else's profile before we merge this.

**Pull request merged**
