### PR TITLE
Backport npm updates

### PR DESCRIPTION
**Pull request by christianbundy**
- scuttlebot => ssb-server
- installed new ssb-server plugins
- upgraded patchcore, ssb-about, and ssb-ws
- added used modules that were missing from `package.json`:
  - lodash
  - run-parallel
- removed `sbot-local-widh-address-fix.js`

### CODE REVIEW

**Comment by christianbundy** [comment]
Looks like the ssb-about and patchcore upgrades are causing issues:

```
TypeError: sbot.about.valueFromStream is not a function
    at api.sbot.pull.stream (/home/christianbundy/src/ssbc/patchwork/node_modules/patchcore/about/obs.js:62:56)
    at /home/christianbundy/src/ssbc/patchwork/node_modules/patchcore/sbot.js:240:28
    at watch (/home/christianbundy/src/ssbc/patchwork/node_modules/mutant/once-true.js:8:7)
    at watch (/home/christianbundy/src/ssbc/patchwork/node_modules/mutant/watch.js:7:5)
    at onceTrue (/home/christianbundy/src/ssbc/patchwork/node_modules/mutant/once-true.js:4:17)
    at Object.stream (/home/christianbundy/src/ssbc/patchwork/node_modules/patchcore/sbot.js:239:11)
    at Object.stream (/home/christianbundy/src/ssbc/patchwork/node_modules/depject/apply.js:18:30)
    at Object.MutantPullValue [as getStream] (/home/christianbundy/src/ssbc/patchwork/node_modules/patchcore/about/obs.js:62:28)
    at Object.listen (/home/christianbundy/src/ssbc/patchwork/node_modules/patchcore/lib/mutant-pull-value.js:32:10)
    at Object.addListener (/home/christianbundy/src/ssbc/patchwork/node_modules/mutant/lib/lazy-watcher.js:85:16)
TypeError: release is not a function
    at Immediate.doRelease [as _onImmediate] (/home/christianbundy/src/ssbc/patchwork/node_modules/mutant/once-true.js:15:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

Rolling back now...

**Comment by mmckegg** [comment]
@christianbundy won't have time to test this for another couple of hours, but I did think of something that broke in patchwork master when we updated ssb-about: **gatherings**

In particular, editing of gatherings. You could probably also backport the new gathering editor, but then .. well, that's a bit of a slippery slope.

**Comment by christianbundy** [comment]
Good call, I've just pushed a commit a few seconds ago that rolls back ssb-about and patchcore. I'll keep testing it out and see if I can find anything else that I can break.

**Comment by christianbundy** [comment]
Closing in favor of #961.

**Pull request closed without merging**
