### PR TITLE
Replace the weird channels view with a nice channel nav popup

### PR DESCRIPTION
**Pull request by pfraze**
This improves the channel selection a bit

screen shot 2016-01-06 at 3 52 08 pm

### CODE REVIEW

**Comment by clehner** [comment]
I like it, except for this horizontal scrollbar:
horizscroll

**Comment by pfraze** [comment]
gross, 1 sec

**Comment by pfraze** [comment]
ok pull and try again

**Comment by clehner** [comment]
Still seeing it intermittently. Adding `overflow-x: hidden` appears to fix it

**Comment by pfraze** [comment]
that's weird, ok done

**Pull request merged**
