### PR TITLE
update ssb-msgs version in ui folder. fixes #158

### LINKED ISSUE #158: error posting in current master
_ssbMsgs2.default.relationsTo is not a function

```
TypeError: _ssbMsgs2.default.relationsTo is not a function
    at /home/mix/projects/patchwork/ui/com/msg-thread.jsx:84:29
    at /home/mix/projects/patchwork/ui/node_modules/pull-stream/sinks.js:15:33
    at /home/mix/projects/patchwork/node_modules/patchwork-threads/index.js:258:25
    at /home/mix/projects/patchwork/node_modules/multicb/index.js:40:13
    at next (/home/mix/projects/patchwork/node_modules/patchwork-threads/index.js:363:7)
    at Object._requests.(anonymous function) (/home/mix/projects/patchwork/ui/node_modules/muxrpc/node_modules/packet-stream/index.js:37:5)
    at PacketStream._onrequest (/home/mix/projects/patchwork/ui/node_modules/muxrpc/node_modules/packet-stream/index.js:139:26)
    at PacketStream.write (/home/mix/projects/patchwork/ui/node_modules/muxrpc/node_modules/packet-stream/index.js:122:41)
    at /home/mix/projects/patchwork/ui/node_modules/muxrpc/pull-weird.js:52:15
    at /home/mix/projects/patchwork/ui/node_modules/muxrpc/node_modules/pull-stream/sinks.js:15:33
```

### PR DESCRIPTION
**Pull request by mixmix**
I think this is the bug that's been plaguing me. (issue#158)

does this look safe @pfraze ?

### CODE REVIEW

**Comment by mixmix** [comment]
merging this should auto-clone https://github.com/ssbc/patchwork/issues/158

**Comment by pfraze** [comment]
Oh! No, `ui/package.json` and `ui/node_modules` should not exist. They got incorrectly carried over from a past version. Will submit a PR to remove `ui/package.json`, and then you'll need to delete `ui/node_modules` in your install

**Comment by pfraze** [comment]
pushed

**Comment by mixmix** [comment]
thanks !

**Pull request closed without merging**
