### PR TITLE
Add appdata and desktop files

### PR DESCRIPTION
**Pull request by ptomato**
Hi, I'm trying to package Patchwork for distribution on Flathub (https://flathub.org) and I thought you might like to have these metadata files as they could be useful for the AppImage build as well. These files are used for providing metadata (descriptions, icons,...) for various app stores on Linux.

### CODE REVIEW

**Comment by mmckegg** [comment]
This looks fine @ptomato. The only issue I can see with merging this is keeping the release info up to date: https://github.com/ptomato/patchwork/blob/535973ce3eb49d76b9e640991bbf38357bd61ae0/assets/nz.scuttlebutt.Patchwork.appdata.xml#L31-L55

**Comment by ptomato** [comment]
Yeah, that seems like (a small amount of) annoying manual work that would have to be done each release. Do you think it should just be removed instead?

**Comment by mmckegg** [comment]
@ptomato yes, probably should just be removed. Unless you want to create a script that pulls this out of the releases tab?

**Comment by ptomato** [comment]
OK, here it is with that section removed.

**Comment by mmckegg** [comment]
Okay, thanks @ptomato, merging!

**Pull request merged**
