### PR TITLE
Fix DuckDuckGo search on spellcheck context menu

### LINKED ISSUE #1002: Spellcheck context menu has an extra horizontal line
I think this might be from #980, cc: @Powersource

### PR DESCRIPTION
**Pull request by christianbundy**
Resolves #1002

### CODE REVIEW

**Comment by Powersource** [comment]
Lol I was just about to submit a PR as well :smile: Yours is prettier tho, will test.

**Comment by Powersource** [comment]
Does this work with other languages? I'm guessing electron is localized.

**Comment by christianbundy** [comment]
Looks like it -- if the context menu has been localized it doesn't look like we're using that localization:

Screenshot from 2019-04-26 11-00-34

**Comment by Powersource** [comment]
Ok so electron probably is, but not [electron-spellchecker](https://github.com/electron-userland/electron-spellchecker/blob/2e093683cf4dafe3a329abc37486997dbd95aab2/src/context-menu-builder.js#L16). Interesting choice for a module about language :P

**Comment by Powersource** [comment]
Seems to work :)

**Comment by christianbundy** [comment]
https://github.com/electron-userland/electron-spellchecker/commit/a1ab6ad8932e3aab46619a48ecf64b5d038b2670#diff-04c6e90faac2675aa89e2176d2eec7d8R22

:wink:

**Pull request merged**
