### PR TITLE
fix rebuild script to work cross-platform

### PR DESCRIPTION
**Pull request by ahdinosaur**
wrote a silly module to fix our windoze woes: [`cross-script`](https://github.com/ahdinosaur/cross-script)

- fixes bug introduced in https://github.com/ssbc/patchwork/pull/513
- reference: https://github.com/ssbc/patchwork/pull/535

TODO

- [x] test on windows
- [x] test on linux
- [x] test on mac
- [ ] test on bsd?

### CODE REVIEW

**Comment by ahdinosaur** [comment]
doesn't actually work on Windows yet: https://github.com/ahdinosaur/cross-script/issues/1

**Comment by ahdinosaur** [comment]
can somebody on windows try this again? :heart:

**Comment by dominictarr** [comment]
@av8ta

**Comment by mmckegg** [comment]
@ahdinosaur failed 😢 

```
> ssb-patchwork@3.4.0 rebuild C:\Users\matt\Code\patchwork-builder\app
> cross-script npm rebuild --runtime=electron --target=$(electron -v) --abi=$(electron --abi) --disturl=https://atom.io/
download/atom-shell

--abi was unexpected at this time.

C:\Users\matt\Code\patchwork-builder\app>  "C:\Users\matt\Code\patchwork-builder\app\node_modules\.bin\\node.exe"  "C:\U
sers\matt\Code\patchwork-builder\app\node_modules\.bin\\..\cross-script\bin.js" npm rebuild --runtime=electron --target=
$(electron -v) --abi=$(electron --abi) --disturl=https://atom.io/download/atom-shell
```

**Comment by ahdinosaur** [comment]
@mmckegg is this using `cmd` or PowerShell?

**Comment by ahdinosaur** [comment]
oooh, i was worried you were using PowerShell which uses `$(subexpression)`, but now i see why it would fail on Cmd: https://ss64.com/nt/syntax-esc.html.

> If a single parameter contains spaces, you can still pass it as one item by surrounding in "quotes" - this works well for long filenames.

maybe fixed with https://github.com/ssbc/patchwork/pull/543/commits/c1b0e145a000b4c06d70548833c71b6de04d3f27. can you try again please? :heart:

**Comment by mmckegg** [comment]
Works now!

I am using powershell, but I suspect that node's shell uses cmd.

**Comment by ahdinosaur** [comment]
woo hoo!

should we merge this meow?

**Comment by mmckegg** [comment]
Sure, as long as it still works on the other platforms 😆

**Comment by av8ta** [comment]
cross-script did the trick for me :)
It's building on windows and linux fine here. Windows builds without spell checking though.

**Comment by mmckegg** [comment]
Okay, this seems to be working pretty well. Gonna merge!

**Pull request merged**
