### PR TITLE
Bump ssb-backlinks

### PR DESCRIPTION
**Pull request by arj03**
This should be much faster especially for onboarding people. See this [issue](https://github.com/ssbc/ssb-ref/issues/36) for details.

### CODE REVIEW

**Comment by christianbundy** [comment]
Thanks! I'm excited to merge this, do you mind if I leave it open for a couple days just to make sure we fix #1253 before adding indexing to the mix?

**Comment by arj03** [comment]
No please. No rush

**Comment by Powersource** [comment]
Got infinite scuttling. Idk if it's related to this PR or conn-stuff but anyway. A lot of logging, I'll post what I can.

```
Exception thrown by PacketStream substream end handler Error {}
Error: unexpected hangup
    at Object.cb (/home/me/prj/ssb/patchwork/node_modules/pull-box-stream/index.js:117:44)
    at drain (/home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:46:23)
    at /home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:63:18
    at /home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:114:13
    at drain (/home/me/prj/ssb/patchwork/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/home/me/prj/ssb/patchwork/node_modules/stream-to-pull-stream/index.js:143:5)
    at Socket.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
Exception thrown by PacketStream substream end handler Error {}
Error: unexpected hangup
    at Object.cb (/home/me/prj/ssb/patchwork/node_modules/pull-box-stream/index.js:117:44)
    at drain (/home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:46:23)
    at /home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:63:18
    at /home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:114:13
    at drain (/home/me/prj/ssb/patchwork/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/home/me/prj/ssb/patchwork/node_modules/stream-to-pull-stream/index.js:143:5)
    at Socket.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
Exception thrown by PacketStream substream end handler Error {}
Error: unexpected end of parent stream
    at PacketStream.destroy (/home/me/prj/ssb/patchwork/node_modules/packet-stream/index.js:71:7)
    at PacketStream.write (/home/me/prj/ssb/patchwork/node_modules/packet-stream/index.js:133:41)
    at /home/me/prj/ssb/patchwork/node_modules/muxrpc/pull-weird.js:58:44
    at /home/me/prj/ssb/patchwork/node_modules/pull-stream/sinks/drain.js:20:24
    at /home/me/prj/ssb/patchwork/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/me/prj/ssb/patchwork/node_modules/packet-stream-codec/index.js:95:24
    at next (/home/me/prj/ssb/patchwork/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:14:9)
    at /home/me/prj/ssb/patchwork/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:16:41
    at Object.cb (/home/me/prj/ssb/patchwork/node_modules/packet-stream-codec/index.js:102:18)
    at drain (/home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:39:14)
Exception thrown by PacketStream substream end handler Error {}
Error: unexpected hangup
    at Object.cb (/home/me/prj/ssb/patchwork/node_modules/pull-box-stream/index.js:117:44)
    at drain (/home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:46:23)
    at /home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:63:18
    at /home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:114:13
    at drain (/home/me/prj/ssb/patchwork/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/home/me/prj/ssb/patchwork/node_modules/stream-to-pull-stream/index.js:143:5)
    at Socket.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
Exception thrown by PacketStream substream end handler Error {}
Error: unexpected end of parent stream
    at PacketStream.destroy (/home/me/prj/ssb/patchwork/node_modules/packet-stream/index.js:71:7)
    at PacketStream.write (/home/me/prj/ssb/patchwork/node_modules/packet-stream/index.js:133:41)
    at /home/me/prj/ssb/patchwork/node_modules/muxrpc/pull-weird.js:58:44
    at /home/me/prj/ssb/patchwork/node_modules/pull-stream/sinks/drain.js:20:24
    at /home/me/prj/ssb/patchwork/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/me/prj/ssb/patchwork/node_modules/packet-stream-codec/index.js:95:24
    at next (/home/me/prj/ssb/patchwork/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:14:9)
    at next (/home/me/prj/ssb/patchwork/node_modules/pull-stream/sinks/drain.js:16:11)
    at /home/me/prj/ssb/patchwork/node_modules/pull-stream/sinks/drain.js:29:15
    at /home/me/prj/ssb/patchwork/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
Exception thrown by PacketStream substream end handler Error {}
Error: unexpected hangup
    at Object.cb (/home/me/prj/ssb/patchwork/node_modules/pull-box-stream/index.js:117:44)
    at drain (/home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:46:23)
    at /home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:63:18
    at /home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:114:13
    at drain (/home/me/prj/ssb/patchwork/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/home/me/prj/ssb/patchwork/node_modules/stream-to-pull-stream/index.js:143:5)
    at Socket.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
Exception thrown by PacketStream substream end handler Error {}
Error: unexpected end of parent stream
    at PacketStream.destroy (/home/me/prj/ssb/patchwork/node_modules/packet-stream/index.js:71:7)
    at PacketStream.write (/home/me/prj/ssb/patchwork/node_modules/packet-stream/index.js:133:41)
    at /home/me/prj/ssb/patchwork/node_modules/muxrpc/pull-weird.js:58:44
    at /home/me/prj/ssb/patchwork/node_modules/pull-stream/sinks/drain.js:20:24
    at /home/me/prj/ssb/patchwork/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/me/prj/ssb/patchwork/node_modules/packet-stream-codec/index.js:95:24
    at next (/home/me/prj/ssb/patchwork/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:14:9)
    at next (/home/me/prj/ssb/patchwork/node_modules/pull-stream/sinks/drain.js:16:11)
    at /home/me/prj/ssb/patchwork/node_modules/pull-stream/sinks/drain.js:29:15
    at /home/me/prj/ssb/patchwork/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
Exception thrown by PacketStream substream end handler Error {}
Error: unexpected hangup
    at Object.cb (/home/me/prj/ssb/patchwork/node_modules/pull-box-stream/index.js:117:44)
    at drain (/home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:46:23)
    at /home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:63:18
    at /home/me/prj/ssb/patchwork/node_modules/pull-reader/index.js:114:13
    at drain (/home/me/prj/ssb/patchwork/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/home/me/prj/ssb/patchwork/node_modules/stream-to-pull-stream/index.js:143:5)
    at Socket.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
...
```
and also a lot of
```
Exception thrown by PacketStream substream end handler Error { errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:183:27)
```

**Comment by Powersource** [comment]
cc @staltz idk if you recognize those stack traces as being conn-related (I mean it doesn't mention conn but maybe an error that's propagated?)

**Comment by staltz** [comment]
@Powersource doesn't seem ssb-conn related to me. Those kind of errors have always been somewhat common in SSB since always.

**Comment by arj03** [comment]
First of all, thanks for testing @Powersource 

I'm with Staltz on the errors. These look like network errors? What happens if you run a `sbot status`? Mine right now looks like this:

```
~/dev/ssb-minimal-pub-server/bin.js status
{
  "progress": {
    "indexes": {
      "start": 838120964,
      "current": 838120964,
      "target": 838120964
    }
  },
  "sync": {
    "since": 838120964,
    "plugins": {
      "last": 838120964,
      "keys": 838120964,
      "clock": 838120964,
      "time": 838120964,
      "feed": 838120964,
      "contacts2": 838120964,
      "backlinks-6CAxOI3f-": 838120964,
      "ssb-chess-index": 838120964,
      "meme": 838120964,
      "private-6CAxOI3f-": 838120964,
      "query": 838120964,
      "search": 838120964,
      "unread-dummy-index": 838120964,
      "peer-invites": 838120964
    },
    "sync": true
  }
}
```

**Comment by Powersource** [comment]
Unfortunately started the regular client instead of this branch again so didn't get to see the index status. Will try to run this branch again now and try to reproduce.

Any way I agree that this issue is probably unrelated to this PR.

**Comment by christianbundy** [comment]
I don't know whether I remember 100% -- when we bump indexes should we be doing releases of all clients? I'm worried that if Patchwork releases with a new SSB-Backlinks then if someone opens and closes Patchwork and then switches to another client then they'll just keep deleting the backlinks directory and starting from scratch. Is that true, or am I tripping?

**Comment by arj03** [comment]
Yes, patchbay is already upgraded ;)

**Comment by christianbundy** [comment]
Sweet, I'm down to merge ASAP. It looks like `package.json` and `package-lock.json` aren't in sync and Travis is failing, if you push a fix I'll merge or I'll try to get to it in the next few days.

**Comment by arj03** [comment]
Thanks @christianbundy. I pushed a merge now.

**Comment by christianbundy** [comment]
I don't think it's a merge conflict, it looks like a conflict between `package.json` and `package-lock.json`. Does `npm ci` work for you locally? I think the fix is usually just `npm install`, which should update `package-lock.json`.

**Comment by arj03** [comment]
Thanks. Latest commit should do it.

**Comment by christianbundy** [comment]
:tada:

**Pull request merged**
