### PR TITLE
Add watchified build scripts

### PR DESCRIPTION
**Pull request by clehner**
This adds auto-rebuild scripts for the JS, CSS, server (auto-restart), and one to run all three.

This also moves the build script from the separate script file into the package.json, using browserify's JSON syntax for the transforms. This allows the config to be shared by browserifyinc and watchify, and results in less code. Some testing should be done on this to make sure that this does not cause a regression of the issue of babel finding presets when symlinked node_modules are used. (It hasn't yet for me).

nodemon is used for restarting the server (which currently requires the client to refresh to reconnect (#255)). I could not find any LESS-specific tool for rebuilding the stylesheets incrementally that worked with having a single entry-point less file importing other less files, but it's quick enough to build them in one shot and nodemon handles running arbitray commands and watching arbitray files, so we use it here for auto-rebuilding the CSS as well.

Ref https://github.com/ssbc/patchwork/issues/273#issuecomment-176297535 and
[%DkiS2KWRQdkMb9U64njPVeFZ4InKKZfIEtBCNMtmhYM=.sha256](http://localhost:7777/#/msg/%25DkiS2KWRQdkMb9U64njPVeFZ4InKKZfIEtBCNMtmhYM%3D.sha256)

### CODE REVIEW

**Comment by pfraze** [comment]
Nice. Funny you moved the build out of JS, because https://github.com/ssbc/patchwork/issues/272 makes me think we may need to move them all into JS for portability. We'll see, but this should be :+1: for now

**Comment by mixmix** [comment]
nice!

**Comment by clehner** [comment]
One problem I have noticed with this is that sometimes watchify has recognizing jsx files. I find it happens sometimes when switching branches, I will start seeing errors like this:
```
/usr/local/src/patchwork/ui/routes.jsx:2
import React from 'react'
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```
When this happens I have to restart watchify. This takes a while, so it would be good to fix this problem.

I think there may be some config option to fix this but I haven't found it yet.

**Comment by clehner** [comment]
Ok, I found that the problem I mentioned was happening because when I was switching branches, I was switching to a branch that didn't have the browserify transforms in package.json, and so browserify or babelify was rereading package.json and not getting the correct options. If the changes in this branch are merged into the other branches then this problem does not occur.

So unless anyone else has issues with this PR, it should be good to merge.

**Comment by pfraze** [comment]
Ok :+1: I havent tested yet but easy to fix if something's wrong, and Im sure there wont be anyway

**Pull request merged**
