### PR TITLE
ui: threads now render 'missing message' cards when a reply refers to a branch that's not found

### PR DESCRIPTION
**Pull request by pfraze**
https://github.com/ssbc/patchwork/issues/88

When a message references a `branch` that's not in the `relatedMessages` results, this code will render the following:

screen shot 2015-11-12 at 12 57 32 pm

Clicking on the blue text expands into a longer explanation:

screen shot 2015-11-12 at 12 57 39 pm

### CODE REVIEW

**Comment by pfraze** [comment]
Here's a thread with 2 replies with the same missing parent, and then a third reply with a different missing parent:

screen shot 2015-11-12 at 1 12 19 pm

**Comment by pfraze** [comment]
Tweaked that help copy to say, "Some of the messages in this thread may reference it."

**Comment by dominictarr** [comment]
:+1:

**Comment by dominictarr** [comment]
It's weird to see that message, because you are telling the user something but not giving them any clues about what they can do about it. That doesn't empower the user.

It would probably be better to download that message, even if it's only shown with a pubkey as id, and not a name...(or something) maybe require a user click to request that message manually from a server...

But, I don't think that is a priority until someone complains about this.

**Comment by pfraze** [comment]
Yeah I'm in agreement about all of that

**Pull request merged**
