### PR TITLE
update sbot to latest

### PR DESCRIPTION
**Pull request by dominictarr**
this fixes the crashing threads problem, as in

https://github.com/ssbc/patchwork/issues/412

https://github.com/ssbc/patchwork/issues/409

this will work on it's own, but also updating patchwork-threads will be even more efficient.
https://github.com/ssbc/patchwork-threads/pull/13

### CODE REVIEW

**Comment by dominictarr** [comment]
merged into 2.10.2

main improvement: no inexplicably slow threads.
need new releases cut @clehner @mmckegg

**Comment by mmckegg** [comment]
@dominictarr Cool, is the only thing that needs updating on patchwork-electron the `patchwork` dep?

**Comment by dominictarr** [comment]
it updates scuttlebot and patchwork-threads, but those will update when you reinstall ssb-patchwork

**Comment by fredhampton** [comment]
@dominictarr What branch of ssb-patchwork had the needed updates

**Comment by mmckegg** [comment]
@dominictarr Oh I see, you haven't pushed the v2.10.2 publish tag to GitHub, but it has been [published to npm](https://www.npmjs.com/package/ssb-patchwork). That confused me a wee bit! Will put up a `patchwork-electron` v2.10.2 mac build real soon 🎆

**Comment by dominictarr** [comment]
sorry! this is all pushed to master now!

**Comment by mmckegg** [comment]
Released mac version! https://github.com/ssbc/patchwork-electron/releases/tag/v2.10.2

Anyone want to do the linux build? Otherwise someone twist my arm and I'll do it too!

**Comment by dominictarr** [comment]
@mmckegg you are on a roll! go ahead and to the linux one too!

**Pull request merged**
