### PR TITLE
Animations

### PR DESCRIPTION
**Pull request by pfraze**
Add animations for transitions and common ui elements

### CODE REVIEW

**Comment by pfraze** [comment]
message fade-ins:

message-fade

(a bit hard to appreciate in this gif)

**Comment by pfraze** [comment]
Composer animate out:

composer-swing

**Comment by pfraze** [comment]
Really fabulous dig buttons:

fabulous-dig

**Comment by mixmix** [comment]
I think the question here is accessibility.
I want to see this running on a shitty old computer :P

**Comment by ahdinosaur** [comment]
> I want to see this running on a shitty old computer :P

@mixmix i doubt these changes alone do much to raise the minimum platform requirements, i reckon there are bigger fish to fry in that sea.

**Comment by pfraze** [comment]
Im going to go ahead and merge, and we can evaluate perf. I do agree we have some config tools in our future

**Pull request merged**
