### PR TITLE
add dark theme

### PR DESCRIPTION
**Pull request by mixmix**
This is the branch dedicated to the dark theme.

selection_376

All theme picking logic was extracted into another PR, as was the extraction of the light theme.

This should give you space and time to hone this a little before we merge this :)

### CODE REVIEW

**Comment by alanshaw** [comment]
@mixmix I hope you don't mind but I scoped the scrollbar styling to linux according to `process.platform`. In macOS the default is to not show the scrollbar unless scrolling and it sort of styles itself accordingly (by virtue of it being grey and semi-transparent), styling the scrollbar using CSS causes it to always appear...

**Comment by alanshaw** [comment]
**OK SO...**

I think I have about 99% of the styles done. It would be rad to get this merged, released, get some feedback and then do a round of fix-em-ups...

@mixmix :thumbsup: :thumbsdown: ?

Here's some screenshots:

screen shot 2017-09-15 at 22 43 52
screen shot 2017-09-15 at 22 44 05
screen shot 2017-09-15 at 22 44 38
screen shot 2017-09-15 at 22 45 09

**Comment by mixmix** [comment]
Looking great. Totally fine to scope linux.
We've been perverting detecting os using a module I've used is-windows
before. I bet there's a family

**Comment by mixmix** [comment]
https://www.npmjs.com/package/is-osx

I'll show test what you've got here when I get home. Will try it on Windows
too.

Looking great from screenshots. I've had people asking me what I'm using
when I've been running it in the office!

**Comment by mmckegg** [comment]
@mixmix Patchwork is already detecting the OS and adding it as a class on the main window. I believe that is what @alanshaw used.

**Comment by mmckegg** [comment]
Whoops, pushed in latest changes from master. Seems to work fine though, hopefully this doesn't hurt anyone 😆 

I suppose this is now safe to merge into master then.

**Comment by mmckegg** [comment]
Noticed this: (the `x` out of place)

screen shot 2017-09-16 at 2 48 14 pm

@mixmix do you think this is something from the 5MB limit warning showing through?

**Comment by mmckegg** [comment]
Okay, fixed the mysterious x. The attachment warning wasn't in the dark theme. Added it. Probably needs styling.

Sorry about my dabbling, hopefully this won't screw up anyone's working directories too much....

**Comment by mmckegg** [comment]
We probably need to find a way to cut down on the duplication between themes at some point. Was that what you were talking about @mixmix with the mixins?

**Comment by mixmix** [comment]
yeah there are two strategies we could have gone for: 
- completely standalone styles
- base default style, with styles merged OVER. 

we've gone for the former here. Let's watch and see. The new feature you had to patch is a good example of ahhh merging perhaps being preferable.

Spun this up on windows. Looks pretty good. The scroll bars aren't dark, so might check out that implementation of the dark bar toggling

**Comment by mixmix** [comment]
oh yeah great Mixins would be a nice strategy @mmckegg ...  do they trump one another if there are multiple defiinitions of e.g. `$backgroundPrimary` ? 

lets kick this down the road tho

**Comment by mixmix** [comment]
woop, looks great in windows !

**Pull request merged**
