### PR TITLE
New electron packager and ignore dist/ when packing

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by dominictarr** [comment]
what does ignore dist do?

**Comment by aredridel** [comment]
I kept getting dist/win packed up inside the mac app if I ran `npm run build:osx` without a clean -- this clarifies that and makes sure that entire directory is ignored.

**Comment by mixmix** [comment]
awesome, I think @pfraze will have to confirm this works (packing osx apps on linux fails for me because of files missing I think)

@aredridel I think this pull request should be into `master` now that `ui-rework-2` has been merged in there

**Comment by pfraze** [comment]
I will be working on it this week, I'll incorporate these changes then. Thanks again @aredridel !

**Comment by aredridel** [comment]
Awesome :) I can poke it again if you need me to.

**Comment by pfraze** [comment]
I ended up reorganizing all of this into the https://github.com/ssbc/patchwork-electron module

**Pull request closed without merging**
