### PR TITLE
Mixmix Msg Chrome

### PR DESCRIPTION
**Pull request by pfraze**
This updates the message chrome to match @mixmix's mockup.

The mockup:
mix-mockup

This PR:
screen shot 2015-11-07 at 7 57 17 pm
screen shot 2015-11-07 at 8 07 09 pm

Not a 100% match, but close. I haven't changed how new replies are indicated yet.

### CODE REVIEW

**Comment by dominictarr** [comment]
One thing i really liked about @mixmix's pitch for it is it has a rational for everything.
And the reasons he gave where clearly consistent and would be applied to other things.
eg. in left-right languages the future is to the right, so put actions on the right. group things with similar functionality.

It was really interesting because you can agree to the principles and immediately know what the correct thing is. In mix's mockup, the dotmenu is on the right, but in your image save is on the right, that feels intuitively wrong to me... but I'm not sure why. Is there a principle we can come up with that rationalizes why it should be one or the other?

**Comment by pfraze** [comment]
Hmm. Good question. 

Putting the dropdown on the right continues the left-to-right flow, which does feel natural.

Putting the save-btn on the right gives it dominance, since top-right is a prominent position, which is good for a commonly-used item.

I think they look good either way.

**Comment by mixmix** [comment]
Thanks for the feedback! I'm really flattered.

It's important to note I'm not a designer. This is as much a note to self
as to you guys. Every time i do some design work i think i'm doing ok, then
when i work with a designer I'm totally humbled by their experience and
skill.

I'll see if i can nab some designers at enspiral for a quick user test when
i get back to nz.

**Comment by pfraze** [comment]
@mixmix sounds great

https://github.com/ssbc/patchwork/issues/65 got hit in this PR. https://github.com/ssbc/patchwork/commit/d8d877c09560cfcf128bdaa4d2755cd969607f61 (https://github.com/ssbc/patchwork/commit/d8d877c09560cfcf128bdaa4d2755cd969607f61#diff-082b1ce5b9da9f71152ff2aa459ba81aR137 specifically) should solve the first issue I quote in https://github.com/ssbc/patchwork/issues/65#issuecomment-154273650. Second issue still exists.

I'll go ahead and swap the search and dropdown btns, because there have been 3 votes for that and 1 for the other (I vote for both). Then I suggest we merge this, and can keep looking at it in the future.

**Comment by pfraze** [comment]
screen shot 2015-11-08 at 7 40 33 pm

@dominictarr @mixmix ok to merge?

**Comment by mixmix** [comment]
not sure what the search / dropdown thing is, but I've been living in `mix-chrome` for the last day and it's **comfy**!!

reckon it's good to merge (conflicts aside)

**Pull request merged**
