### PR TITLE
Block and Unblock users buttons

### PR DESCRIPTION
**Pull request by gmarcos87**
Regarding the discussions about the need to filter the content I see in my feed and have the ability to decide not to see certain content, I add the block and unblock buttons.
It is the same function that already exists in patchbay.
Anyway, this is one more tool, it is not the solution to the conflicts that exist behind the blocked comments, it is a smokescreen that allows to make more bearable the daily experience in our social network.

To have some context see: %sH1wpo1g7UySFR69OarqFW7ZTJjHOjdYB356derLRH8=.sha256 and %dRuGqDTklt1VqHOEcdJkwgbUrMyELenSCscSbGz+8KQ=.sha256

### CODE REVIEW

**Comment by mmckegg** [comment]
Mostly happy with this. Thanks @gmarcos87.

I'm gonna make a few style tweaks then merge! Will also try and get that [patchcore pull](https://github.com/ssbc/patchcore/pull/36) in too!

**Comment by mixmix** [comment]
This looks really good @gmarcos87 
I think the only piece that is missing is the description text about when block means. (I've have feedback from minority community that all the security and safety means nothing if people don't know what the system is doing).

In patchbay I added this section : 
```js
h('section -blocking', [
  when(ImBlockingThem,
    h('button', { 'ev-click': () => unblock(id, console.log) }, 'unblock'),
    h('button', { 'ev-click': () => block(id, console.log) }, 'BLOCK')
  ),
  h('div.explainer', [
    "Blocking tells everyone you don't want to communicate with a person.",
    h('ul', [
      h('li', 'You will no longer receive messages from this person'),
      h('li', "This person won't get any new information about you (including this block)"),
      h('li', "Your followers will see you have blocked this person - their apps need to know so that they don't pass your information on."),
    ])
  ])
])
```

and had css which only showed this on hover : 
```css
     -blocking {
        margin-left: 8rem
        position: relative

        button {}

        div.explainer {
          visibility: hidden
          position: absolute
          background: #fff
          width: 24rem
          left: 1rem
          bottom: 2rem
          padding: .5rem
          box-shadow: rgba(0, 0, 0, 0.2) 2px 2px 8px

          ul {
            font-size: .8rem
            padding-left: 1rem
          }
        }

        :hover {
          div.explainer {
            visibility: visible
          }
        }
```

**Comment by mmckegg** [comment]
Good thinking @mixmix!

**Comment by mixmix** [comment]
I propose we add @gmarcos87 as a contributor so it's easier to pull in and test his PRs

**Comment by mmckegg** [comment]
@mixmix He already is! 😄

**Comment by mixmix** [comment]
I assumed he wasn't because the PR is from his fork. I notice I am lazy and don't want to test running people's code if I have to add their remote repo then pull in from over there ... 

I guess the specific request is - **please push branches to this repo** , it means open PRs are easier for everyone to test and work on.

**Comment by gmarcos87** [comment]
Great!!! Superpowers !!! Now I can do git push --force !!
I'm kidding, thank you so much for this privilege. I am very happy to be able to collaborate and see how the project progresses. In addition to that, at home we enjoy much of the published content and the discussions that arise.

**Comment by mixmix** [comment]
<3

**Comment by mmckegg** [comment]
@mixmix 

> I guess the specific request is - please push branches to this repo , it means open PRs are easier for everyone to test and work on.

Yeah this is true. But I've been using the "view command line options" button on github to get a handy copy and paste which works okay enough. It suggests something like this (avoiding the need for a remote):

```sh
git checkout -b Happy0-updates_msg master
git pull https://github.com/Happy0/patchwork.git updates_msg
```

**Comment by mixmix** [comment]
Ok idea, but i can't push to the branch for any cheeky patches...

**Pull request merged**
