### PR TITLE
add .nvmrc for easy `nvm use`

### PR DESCRIPTION
**Pull request by mixmix**
nvm will check for this dotfile and use that for the version you're refering to. This lets you just call
`nvm install` or 
`nvm use`

without having to specify a version.
It has the added bonus of being a clear way to signal the preferred node version to use, which I like a lot

### CODE REVIEW

**Comment by pfraze** [comment]
:+1: @mixmix :star:

**Comment by mixmix** [comment]
please, I'm just polishing!

**Comment by pfraze** [comment]
well I really appreciate it!

**Comment by mixmix** [comment]
looking forward to helping out more, where possible

**Pull request merged**
