### PR TITLE
Patchwork v2

### PR DESCRIPTION
**Pull request by pfraze**
This massive PR replaces the UI with one written in React.

### CODE REVIEW

**Comment by pfraze** [comment]
@dominictarr @mixmix I suggest we merge this into master, but dont deploy yet

**Comment by pfraze** [comment]
Almost ready to merge! Going to do some small bug fixing this evening, and hopefully merge it up by midnight

**Comment by mixmix** [comment]
awesome, been watching those branches collapse in.
Good work !

**Comment by pfraze** [comment]
thanks @mixmix !

need to do a bit more work, so I'm going to hold off till tomorrow

**Pull request merged**
