### PR TITLE
Context menu

### PR DESCRIPTION
**Pull request by clehner**
Here is a context menu. It includes up to four things:
- Open Link
- Copy Link Location
- Save Image As
- Copy Image Location

I think it might be better to copy message IDs instead of localhost link/image URLs where possible but I haven't implemented that yet.

### CODE REVIEW

**Comment by pfraze** [comment]
:+1: you :guitar: will review and merge tomorrow

**Comment by pfraze** [comment]
This is a great start. It needs to have a little more intelligence about the kinds of objects and links in Patchwork.

 1. Open Link: a-ok
 2. Copy Link Location: if the link is to a message, user, or blob, it should get their SSB ID instead of the HTTP url. If the link is to a website, it should get the HTTP URL.
 3. Copy Image Location: same story.
 4. Save Image As: needs to set a good default name on the save-as dialog, because the hash is not any good. The best way to do this would be, to use the `alt` attribute on the image, and make sure the alt is always populated across the UI. (It currently is populated for inline images on a post, but not for profile pics.)

**Comment by pfraze** [comment]
@clehner if you wont have time to make those changes, let me know and I'll do them.

**Comment by clehner** [comment]
@pfraze that makes sense. I'll update it to do those things

**Comment by clehner** [comment]
"Save Image As" now gets the filename from the name suggested in the URL if it exists, which works for inline attachments and profile pics, and falls back to `alt` otherwise.
I also added some text editing items following the behavior of web browsers and text editors.
That's about all I have in mind to add right now

**Comment by pfraze** [comment]
Great, thank you for the contribution!

**Comment by pfraze** [comment]
closes https://github.com/ssbc/patchwork/issues/170

**Pull request merged**
