### PR TITLE
Channels

### PR DESCRIPTION
**Pull request by pfraze**
Replaces https://github.com/ssbc/patchwork/pull/178, same functionality as that PR but called channels instead of topics (including in the msg schema)

### CODE REVIEW

**Comment by pfraze** [comment]
@dominictarr you ok with the channel change? This updates the post message schemas (from `.topic` to `.channel`)

**Comment by dominictarr** [comment]
@pfraze but where is the pr for ssb-msg-schemas?

**Comment by pfraze** [comment]
Oh, not yet done. The change will be to add a `channel: String` to the `type: post`. I just manually set that attribute in this PR.

**Comment by dominictarr** [comment]
if it's not easier to make the pr to that module then we are doing something wrong

**Comment by pfraze** [comment]
catch-the-bubbles
ok gimme a sec

**Comment by pfraze** [comment]
https://github.com/ssbc/ssb-msg-schemas/pull/13

**Pull request merged**
