### PR TITLE
Match private message avatar pair edges

### PR DESCRIPTION
**Pull request by qubist**
Part of a fix for #1074. This fixes the issue for the dark style. there are some inconsistencies between dark and light styles, so I didn't know how to fix it there.

### CODE REVIEW

**Comment by Powersource** [comment]
Thanks for the PR :)

Hmm I think it works in conversations between 2 people, but when there's 3 or more, the people in "the middle" of the list have images with all round corners.

And if you want to, you can add an entry about this to the changelog, like [this](https://github.com/ssbc/patchwork/pull/1054/commits/6633467f910914a802bac0ad80879d81b620311c)

**Comment by qubist** [comment]
I think that about does it. It would be great to have someone more familiar with the styles code look over this.

**Comment by qubist** [comment]
After more testing, I have found an edge case: When I send a private message to myself I see an avatar image with rounded corners on the right side and not the left.

p

Instead, I should see an avatar image with all corners rounded.

This is caused by my avatar image being considered to have the tag `last-child`. Does anyone what code applies these tags? Searching for `first-child` or `last-child` in the codebase yields nothing

**Comment by qubist** [comment]
I'm now confident this is ready for mere.

**Comment by christianbundy** [comment]
This looks really great, thank you! Just merged into `master` and I can confirm that this looks great on both themes. :rocket:

**Pull request merged**
