### PR TITLE
use ssb-blobs module instead of scuttlebot's built in blobs plugin

### PR DESCRIPTION
**Pull request by dominictarr**
this branch tests sbot with the new blobs plugin - now blobs are requested on demand - so for one, this won't download everything in the case of a new sync.

### CODE REVIEW

**Comment by dominictarr** [comment]
unless patchwork attempts to render every message? @pfraze

**Comment by pfraze** [comment]
Are you going to remove the old blobs code?

**Comment by pfraze** [comment]
Only time blobs get requested in Patchwork is for rendering profile images, or embedded images, or when somebody clicks the link to a blob.

**Comment by pfraze** [comment]
The multiple-hop want/have gossip solution looks promising.

**Comment by dominictarr** [comment]
yeah, to really test, exit patchwork `cd ~/.ssb; mv blobs _blobs; mkdir blobs`
then restart patchwork. since patchwork already checks `blobs.has`

**Comment by clehner** [comment]
i'm testing this now and it seems to be working. are there any concerns before i merge this?

**Comment by dominictarr** [comment]
I was thinking the next step would be to have pubs that use both new and old strategies (and then automatically disable old after some point). but it should be fine to merge this into patchwork.

**Pull request closed without merging**
