### PR TITLE
add subscribe channels list

### PR DESCRIPTION
**Pull request by seanc**

### CODE REVIEW

**Comment by ahdinosaur** [comment]
hey @seanc, thanks for the contribution. have you seen https://github.com/ssbc/patchwork/pull/547?

there's now a "More Channels..." button

more-channels

which takes you to a channels page, ordered by latest post but with styles to mark channels you are subscribed to:

more-channels1

does this solve your use case or do you still feel that this change adds something that is currently missing? and if so, what problem do you feel this addresses?

churrrrrrrrrrrr :cat:

**Comment by seanc** [comment]
mainly i wanted a place to see exactly what channels i subscribed to instead of having to look through a large list polluted with other channels as well :P

**Comment by mmckegg** [comment]
I think this could probably be solved by moving subscribed channels to the top of the all channels list!

The all channels page could also do with some more sorting. For example, ranking by number of posts (or at least showing it).

**Comment by mmckegg** [comment]
Inspired by this pull request and #574, I've gone ahead and added a new "More" menu to the top bar that gives a full list of subscribed channels from any page.

screen shot 2017-06-30 at 12 52 49 pm

@seanc Does this solve it for you? I didn't really want to add more stuff to the Public sidebar as it is already a bit cluttered.

**Comment by seanc** [comment]
looks good to me! i'm open for anything easily accessible.

**Pull request closed without merging**
