### PR TITLE
npm install ssb-patchwork; patchwork

### PR DESCRIPTION
**Pull request by dominictarr**
installing and running patchwork is now simpler than ever.
mainly updated deps (chloride) and added `bin.js`. also updated documentation to refect simpler dependencies.

### CODE REVIEW

**Comment by pfraze** [comment]
:+1:

**Comment by dominictarr** [comment]
merged into 1.1.1

**Comment by dominictarr** [comment]
according to the @paixaop (maintainer of node-sodium) my changes that make sodium install without automake may not build on other linuxes... but it works for me, on archlinux, and on travis, on ubuntu.
I say we just roll with this until we find something that it doesn't work on

**Comment by steefmin** [comment]
I think I have found such a situation. I'm running patchwork on a raspberry pi. It always falls back to the JS crypto, so I tried fixing it by building sodium (`npm install sodium`) myself and copying sodium.node to /chloridedown/build/Release/, as it tells me that's what's missing. 

However this breaks decrypting: 
```
Failed to process message [Error: failed to decrypt] Error: failed to decrypt
    at Object.<anonymous> (/usr/lib/node_modules/ssb-patchwork/node_modules/scuttlebot/plugins/private.js:26:27)
    at /usr/lib/node_modules/ssb-patchwork/node_modules/secure-scuttlebutt/node_modules/level-sublevel/shell.js:102:12
    at /usr/lib/node_modules/ssb-patchwork/node_modules/secure-scuttlebutt/node_modules/level-sublevel/nut.js:121:19
  Error: argument n must be 32 bytes long
    at Error (native)
    at Object.exports.multibox_open (/usr/lib/node_modules/ssb-patchwork/node_modules/private-box/index.js:45:16)
    at Object.exports.unbox (/usr/lib/node_modules/ssb-patchwork/node_modules/ssb-keys/index.js:329:16)
    at Object.<anonymous> (/usr/lib/node_modules/ssb-patchwork/node_modules/scuttlebot/plugins/private.js:25:30)
    at apply (/usr/lib/node_modules/ssb-patchwork/node_modules/muxrpc-validation/index.js:171:15)
    at Object.<anonymous> (/usr/lib/node_modules/ssb-patchwork/node_modules/muxrpc-validation/index.js:62:14)
    at Object.<anonymous> (/usr/lib/node_modules/ssb-patchwork/node_modules/secret-stack/util.js:80:17)
    at Object.<anonymous> (/usr/lib/node_modules/ssb-patchwork/node_modules/hoox/index.js:3:17)
    at Object.hooked [as unbox] (/usr/lib/node_modules/ssb-patchwork/node_modules/hoox/index.js:10:15)
    at /usr/lib/node_modules/ssb-patchwork/api/processor.js:386:40 %4xaCtru5h8RHB+236mbN97vDr/Yg6/QBf0OG0DEkSw8=.sha256 { previous: '%tHW1HbjY76LxkzWBTSS6LvXbAgn7PLzOMVrfOmar6bQ=.sha256',  author: '@ppdSxn1pSozJIqtDE4pYgwaQGmswCT9y15VJJcXRntI=.ed25519',
  sequence: 5,
  timestamp: 1461958696119,
  hash: 'sha256',
  content: 'qHWktsN9c3EVwgik65cEQHknljpELMwAZSPT0zMZHA9mrgqeLz4VzIeUFzpihvrN27W+IewvlwY+enUZ+EzSVzV7DdcYcceMoXu2bfQ+mySFJPn/h8M38nLyq/RJd02TdbB3bFFZwWtvk5dwZzV9rMbylK2AS98eQ6ylKOSNWgVsNg5mC8VV8DsSB5uDUxuASW6ZsuZk+gZGGhm74ImyaHCaqPmCDyF$
  signature: 'aT3Zzr1r6GnvF8rK2lbDRxumndMvRhmrZ92kBuEbjJoJ2Krvm4lTDTrulM1T0MMIPe9RbPDHpCxmkcYHmfaYBQ==.sig.ed25519' }
```
Or am I using this incorrecly?

**Comment by steefmin** [comment]
nvm, :grin: had to get sodium.a and sodium.node from chloridedown.

**Pull request merged**
