### PR TITLE
Create Content Warnings (WIP)

### PR DESCRIPTION
**Pull request by marylychee**
We made the ability to make content warnings on messages!! 

It also saves the draft state of message text and content warnings 😎 

Next actions: 

- improve CSS styles and colors for both reading/creation of CWs for dark/light mode
- toggle button for CW, so input not always there?
- gatherings? do they need CWs? 

✨ 🍐 programing w/ @mmckegg and @cinnamon-bun  ✨

image

image

### CODE REVIEW

**Comment by mmckegg** [comment]
@cinnamon-bun @marylychee 

Something else I just thought of is **handling #channel hashtags** in the content warning! Maybe we need to schedule another peering session?

**Comment by marylychee** [comment]
image

Dark theme now looks better

image

Same with light

**Comment by marylychee** [comment]
oh yeah @mmckegg re: hashtags https://github.com/ssbc/patchwork/issues/1164


> 
>     Autocomplete hashtags
>     Put hashtags in the mentions array (update ssb-mentions?)
>     Autocomplete emoji shortcodes and convert them into unicode characters
> 
>

**Comment by cinnamon-bun** [comment]
Looks great!

I'd support merging this now and adding the extra credit hashtag features as another PR.

**Pull request merged**
