### PR TITLE
change to AGPL-3.0 license

### PR DESCRIPTION
**Pull request by ahdinosaur**
[%cuMtZxypqNBIKQlzxJAq7HrfmuUR6TiElJaQfoxGsRg=.sha256](https://viewer.scuttlebot.io/%25cuMtZxypqNBIKQlzxJAq7HrfmuUR6TiElJaQfoxGsRg%3D.sha256)

---

- [x] @mmckegg
- [x] @olizilla
- [x] @pietgeursen
- [x] @peterbraden
- [x] @mixmix (thumbs-up on ssb thread)
- [ ] @meleyal
- [ ] @ralphtheninja
- [ ] @dmamills
- [ ] @dominictarr

### CODE REVIEW

**Comment by ahdinosaur** [comment]
my understanding is we need consensus from all "major" [contributors](https://github.com/ssbc/patchwork/graphs/contributors) to re-license. by far most of the project has been written by @mmckegg, but other contributors with size-able contributions are:

- @mixmix 
- @olizilla 
- @pietgeursen 
- @meleyal 
- @ralphtheninja 
- @dmamills 
- @peterbraden 
- @dominictarr 

can y'all (re-)post a :+1: if you consent to the re-license? churrrr. :cat:

**Comment by mmckegg** [comment]
👍

**Comment by peterbraden** [comment]
Thumbs up.

**Comment by pietgeursen** [comment]
👍

**Comment by olizilla** [comment]
✨ 🎷 🐩 👍

**Comment by mmckegg** [comment]
@ahdinosaur what counts as a major contributor?

**Comment by ahdinosaur** [comment]
my loose understanding of copyright in open source comes from:

- ["Producing OSS" Background on Copyright Assignment and Ownership](http://www.producingoss.com/en/copyright-assignment.html)
- [_Why does the Free Software Foundation get copyright assignments from contributors_](https://www.gnu.org/licenses/why-assign.html)
- [The Free Software Foundation on Legal Matters](https://www.gnu.org/prep/maintain/maintain.html#Legal-Matters)
- [The core Copyright documents in FSF Projects](http://git.savannah.gnu.org/cgit/gnulib.git/tree/doc/Copyright)

> what counts as a major contributor?

@mmckegg somewhere i read someone defining a "major contributor" as someone who contributes more than 10 lines of non-trivial code. it has to do with the minimum contribution that someone could reasonably claim copyright over.

but to be honest, reading through the licenses ([gpl section 13](https://www.gnu.org/licenses/gpl-3.0.html#section13), [agpl section 13](https://www.gnu.org/licenses/agpl-3.0.html#section13)), we may not even need consensus from all "major contributors", and can upgrade to AGPL from GPL without any fancy process.

any objections to merge right meow?

**Comment by mmckegg** [comment]
I say go for it! @ahdinosaur

**Pull request merged**
