### PR TITLE
Improved composer

### PR DESCRIPTION
**Pull request by pfraze**
screen shot 2015-11-11 at 2 30 25 pm
screen shot 2015-11-11 at 2 30 30 pm

Adds drafts (to non-replies), automatic resizing of the textarea to fit text, and cmd/ctrl+enter to submit

Drafts still need a little work, but they're serviceable for now. The composer automatically saves them to the browser window's localstorage on every edit, so you can leave the composer and come back with no issue.

### CODE REVIEW

**Comment by pfraze** [comment]
https://github.com/ssbc/patchwork/issues/89

**Comment by pfraze** [comment]
@dominictarr @mixmix rfr

**Comment by dominictarr** [comment]
what is happening here, are those drafts, basically?

**Comment by pfraze** [comment]
Yes

**Pull request merged**
