### PR TITLE
change the way ipc is required to be from electron module

### PR DESCRIPTION
**Pull request by mixmix**
electron was throwing errors, wanted this sort of require. 

I'm having other catasrophic errors so not sure this is ready for merge, but wanted to throw this in in case it's useful

### CODE REVIEW

**Comment by mixmix** [comment]
errors I was getting were : 
```
(electron) ipc module is deprecated. Use require("electron").ipcMain instead.
Module version mismatch. Expected 47, got 46.
App threw an error when running [Error: Module version mismatch. Expected 47, got 46.]
/home/mix/projects/patchwork/node_modules/libsodium/dist/modules/libsodium.js:14
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if(!ret&&filename!=nodePath["resolve"](file

Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:140:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:140:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (/home/mix/projects/patchwork/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/mix/projects/patchwork/node_modules/leveldown/leveldown.js:4:46)


```

**Comment by mixmix** [comment]
here's the bug I'm getting after I make these changes :  
https://github.com/ssbc/patchwork/issues/220

**Comment by pfraze** [comment]
Hey @mixmix, those are actually two separate issues.

The "Error: Module version mismatch. Expected 47, got 46." is what's killing the process, and that's because the newest electron requires node v5. I recommend switching to v5, nuking your node_modules, and reinstalling.

The "(electron) ipc module is deprecated. Use require("electron").ipcMain instead." message is a deprecation notice that won't have any negative effects. It's going to take a little time to migrate fully, so I just opened an issue at https://github.com/ssbc/patchwork/issues/216. This PR only half-updates and starts using the new API, and actually causes a break in functionality as a result, so I'm going to close it.

**Comment by mixmix** [comment]
sweet, thanks for the clear breakdown

**Pull request closed without merging**
