### PR TITLE
Tweaks and fixes (tracking PR)

### PR DESCRIPTION
**Pull request by pfraze**
Bundling together a bunch of minor fixes. I'll document them when done.

### CODE REVIEW

**Comment by pfraze** [comment]
Closes https://github.com/ssbc/patchwork/issues/283

**Comment by pfraze** [comment]
Closes https://github.com/ssbc/patchwork/issues/269

**Comment by dominictarr** [comment]
did you publish?

**Comment by pfraze** [comment]
@dominictarr not yet, I've been accumulating updates... not sure why though. I'll go ahead and publish

**Comment by pfraze** [comment]
published `2.6.2`

**Comment by dominictarr** [comment]
just publish everything! I've published sbot at 3 or 4 times today.

**Pull request merged**
